#!/usr/bin/env php
<?php

ini_set('display_errors', '1');
if (function_exists('pcntl_async_signals')) {
    pcntl_async_signals(true);
} else {
    declare(ticks=1);
}

require __DIR__ . '/vendor/autoload.php';

// If profiling is requested, set it up now. Profiling can be enabled from the
// command line by providing XHProf location, e.g.
// RECMAN_PROFILE=http://localhost/xhprof ./console ...
if ($profilerBaseUrl = getenv('RECMAN_PROFILE')) {
    $profiler = new \RecordManager\Base\Utils\Profiler($profilerBaseUrl);
    $profiler->start();
}

// Register a signal handler so that any shutdown functions run if execution is
// interrupted
$signalHandler = function ($signo) {
    exit(255);
};
if (function_exists('pcntl_signal')) {
    pcntl_signal(SIGINT, $signalHandler);
    pcntl_signal(SIGTERM, $signalHandler);
}

// Handle basepath and config overrides ("--config.Section.parameter = value"):
$basepath = null;
$overrides = [];
$remainingArgs = [];
foreach ($_SERVER['argv'] as $parameter) {
    if (!str_starts_with($parameter, '--') || !str_contains($parameter, '=')) {
        $remainingArgs[] = $parameter;
        continue;
    }
    $parsed = @parse_ini_string(substr($parameter, 2));
    if (false === $parsed) {
        $remainingArgs[] = $parameter;
        continue;
    }
    if (isset($parsed['basepath'])) {
        $basepath = $parsed['basepath'];
    } else {
        reset($parsed);
        $key = key($parsed);
        if (preg_match('/^config\.([^.]+)\.(.+)/', $key, $matches)) {
            $overrides[$matches[1]][$matches[2]] = $parsed[$key];
        } else {
            $remainingArgs[] = $parameter;
        }
    }
}
$_SERVER['argv'] = $remainingArgs;
$_SERVER['argc'] = count($remainingArgs);

define('RECMAN_BASE_PATH', $basepath ?: getenv('RECMAN_BASE_PATH') ?: __DIR__);

$app = Laminas\Mvc\Application::init(require 'conf/application.config.php');
$sm = $app->getServiceManager();
if ($overrides) {
    $configReader = $sm->get(\RecordManager\Base\Settings\Ini::class);
    $configReader->addOverrides('recordmanager.ini', $overrides);
}
return $sm->get(\RecordManager\Base\ConsoleRunner::class)->run();
