<?php
/**
 * MARC Record Driver Test Class
 *
 * PHP version 7
 *
 * Copyright (C) The National Library of Finland 2020.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category DataManagement
 * @package  RecordManager
 * @author   Ere Maijala <ere.maijala@helsinki.fi>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://github.com/NatLibFi/RecordManager
 */
namespace RecordManagerTest\Base\Record;

use RecordManager\Base\Record\Forward;

/**
 * FORWARD Record Driver Test Class
 *
 * @category DataManagement
 * @package  RecordManager
 * @author   Ere Maijala <ere.maijala@helsinki.fi>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://github.com/NatLibFi/RecordManager
 */
class ForwardTest extends RecordTest
{
    /**
     * Test FORWARD Record handling
     *
     * @return void
     */
    public function testForward1()
    {
        $record = $this->createRecord(Forward::class, 'forward1.xml');
        $fields = $record->toSolrArray();
        unset($fields['fullrecord']);

        $expected = [
            'record_format' => 'forward',
            'ctrlnum' => 'elonet_elokuva_1511500',
            'publishDate' => '2011',
            'title' => 'Le Havre',
            'title_alt' => [
                0 => 'Mannen från Le Havre',
                1 => 'El Havre',
                2 => 'El Puerto',
                3 => 'El Puerto',
                4 => 'Le Havre: el puerto de la esperanza',
                5 => 'Hof mivtahim',
                6 => 'Miracolo a Le Havre',
                7 => 'To limani tis Havris',
                8 => 'Havras',
                9 => 'O Porto',
                10 => 'Czlowiek z Hawru',
                11 => 'Miraklet i Le Havre',
                12 => 'Umut Limani',
                13 => 'Kikötői történet',
                14 => 'Gavr',
                15 => 'Le Havre: Sadamalinn',
            ],
            'title_full' => 'Le Havre',
            'title_short' => 'Le Havre',
            'title_sort' => 'Havre',
            'description' => 'Marcel Marx, a former author and a well-known'
                . ' bohemian, has retreated into a voluntary exile in the port city'
                . ' of Le Havre, where he feels he has reached a closer rapport with'
                . ' the people serving them in the occupation of the honourable, but'
                . ' not too profitable, of a shoe-shiner. He has buried his dreams'
                . ' of a literary breakthrough and lives happily within the triangle'
                . ' of his favourite bar, his work, and his wife Arletty, when fate'
                . ' suddenly throws in his path an underage immigrant refugee from'
                . ' the darkest Africa.<br /><br />As Arletty at the same time gets'
                . ' seriously ill and is bedridden, Marcel once more has to rise'
                . ' against the cold wall of human indifference with his only weapon'
                . ' of innate optimism and the unwavering solidarity of the people'
                . ' of his quartier, but against him stands the whole blind'
                . ' machinery of the Western constitutionally governed state, this'
                . ' time represented by the dragnet of the police, moment by moment'
                . ' drawing closer around the refugee boy.<br /><br />It\'s time for'
                . ' Marcel to polish his shoes and reveal his teeth. Marcel Marx,'
                . ' entinen kirjailija, elää Ranskassa Le Havressa vaatimattomasti'
                . ' kengänkiillottajana vaimonsa Arlettyn kanssa. Satamakaupungissa'
                . ' kuohuu: tavarakontista löydetään laittomia'
                . ' afrikkalaissiirtolaisia. Eräs pakolaisista, nuori Idrissa,'
                . ' juoksee karkuun poliiseilta. Seuraavana päivänä Marcel löytää'
                . ' pojan satamasta. Komisario Monet osuu paikalle, mutta Marcel ei'
                . ' ilmianna karkulaista. Yön turvin mies vie ruokaa Idrissalle ja'
                . ' laittaa paperipussiin myös rahaa.<br /><br />Kotona Laika-koira'
                . ' on levoton: Arletty ei voi hyvin. Naapuri, Yvette, vie'
                . ' pariskunnan sairaalaan, mutta tohtori Becker kehottaa Marcelia'
                . ' palaamaan kotiin. Marcel löytää Idrissan vajastaan. Poika on'
                . ' tullut maksamaan velkansa ja kertoo haluavansa Lontooseen'
                . ' äitinsä luo. Marcel päättää auttaa ja antaa pojalle'
                . ' piilopaikan.<br /><br />Arletty kuulee tohtorilta, että hänen'
                . ' elämänsä on ihmeen varassa. ”Ihmeitä ei tapahdu minun'
                . ' korttelissani”, nainen tuumaa ja kieltää kertomasta tilansa'
                . ' vakavuutta puolisolleen. Marcelilla on huolta myös Idrissasta,'
                . ' mutta koko hänen naapurustonsa on suureksi avuksi. Ainoastaan'
                . ' vastapäisen talon vanhus soittaa poliisille'
                . ' siirtolaishavainnostaan. Komisario Monet kehottaa Marcelia'
                . ' varomaan naapuriaan.<br /> <br />Marcel ryhtyy selvittämään,'
                . ' miten Idrissa löytäisi äitinsä Lontoosta. Hän jättää pojan'
                . ' Yvetten hoitoon ja lähtee Calais’hen tapaamaan pakolaisleirillä'
                . ' olevaa Idrissan isoisää. Pakolaiskeskuksen'
                . ' maahanmuuttoviranomaisia Marcel hämmentää väittämällä kivenkovaa'
                . ' olevansa sukua, ”perheen albiino”. Isoisä antaa matkaohjeet ja'
                . ' osoitteen. Sillä välin Idrissa karkaa Yvetten luota'
                . ' kiillottamaan kenkiä asemalle. Marcelin naapuri yrittää ottaa'
                . ' pojan kiinni, mutta Marcelin työtoveri Chang tulee hätiin ja'
                . ' poika pääsee jälleen turvaan. <br /><br />Sairaalan'
                . ' vierastunnilla Arletty valehtelee tilastaan aviomiehelleen. Hän'
                . ' kieltää hoitojensa vuoksi Marcelia tulemasta tervehtimään ja'
                . ' käskee tätä palaamaan kahden viikon päästä ja tuomaan hänen'
                . ' keltaisen leninkinsä. Yvetten ja kapakoitsija Clairen kanssa'
                . ' Arletty ei vaihda kuulumisia sen pirteämmin, vaan on'
                . ' huonokuntoinen ja väsynyt.<br /><br />Komisario Monet tekee'
                . ' tutkimuksiaan. Hän tarkkailee Marcelin liikkeitä ja kyselee'
                . ' vihanneskauppiaalta tietoja miehestä. Ananas muassaan hän menee'
                . ' myös Clairen baariin. Claire häätää asiakkaat pois ja istahtaa'
                . ' juttusille Monet’n kanssa. He ovat vanhoja tuttuja; komisario'
                . ' toimitti Clairen aviomiesvainaan telkien taa.<br /><br />Marcel'
                . ' sopii satamassa Idrissan pakojärjestelyistä. Venekyytiin'
                . ' tarvitaan 3000 euroa. Ystävät ehdottavat, että Marcel'
                . ' järjestäisi muodikkaan tukikonsertin. Kun Marcel saa hierottua'
                . ' paikallisen rock-legendan Little Bobin ja tämän kipakan vaimon'
                . ' Mimien välille sovinnon, voidaan konsertti järjestää. Marcel'
                . ' itse erehtyy päivästä ja joutuu lähettämään Idrissan sairaalaan'
                . ' Arlettyn mekkoa viemään. Idrissa kehottaa Arlettya paranemaan'
                . ' pian, sillä Marcel ei pärjää ilman vaimoaan.<br /><br />Little'
                . ' Bobin konsertti on menestys, ja Marcel saa tarvittavan summan'
                . ' kasaan, ennen kuin poliisit saapuvat. Tilanne kotikulmilla käy'
                . ' kuumaksi, ja Monet varoittaa Marcelia viime tipassa. Poliisit'
                . ' rynnivät kengänkiillottajan asuntoon, mutta Idrissa pakenee'
                . ' ikkunasta. Hänet kuskataan satamaan vihanneskärryissä. Poika'
                . ' saadaan veneeseen ja raha-asiat hoidettua, kun poliisit'
                . ' saartavat sataman. Monet saapuu hätiin ja on tarkistavinaan'
                . ' laivan, jossa Marcel ja Idrissa ovat. Hän ei ilmianna'
                . ' pakolaista, vaan poika pääsee matkaan. Marcel ja Monet'
                . ' ystävystyvät.<br /><br />Sairaalassa on tapahtunut ihme:'
                . ' Arletty on toipunut ja pariskunta pääsee palaamaan kotiin.'
                . ' Kotona kirsikkapuu kukkii.<br /><br /><i>Teksti: Suomen'
                . ' kansallisfilmografia / Tytti Rantanen 2016</i>',
            'topic_facet' => [
                0 => 'ananas',
                1 => 'auttaminen',
                2 => 'avioliitto',
                3 => 'baarit',
                4 => 'kauppiaat',
                5 => 'koira',
                6 => 'konsertit',
                7 => 'laiton maahanmuutto',
                8 => 'laivat',
                9 => 'Le Havre',
                10 => 'maahanmuuttajat',
                11 => 'maahanmuuttopolitiikka',
                12 => 'naapuruus',
                13 => 'pakolaiset',
                14 => 'pakolaisleirit',
                15 => 'ihmeparantuminen',
                16 => 'poliisit',
                17 => 'Ranska',
                18 => 'ranskan kieli',
                19 => 'ravintolat',
                20 => 'rock',
                21 => 'sairastuminen',
                22 => 'sairaalat',
                23 => 'satamat',
                24 => 'siirtolaiset',
                25 => 'siirtolaisuus',
                26 => 'sosiaaliset ongelmat',
                27 => 'taudit',
                28 => 'viranomaiset',
                29 => 'vähävaraisuus',
                30 => 'ystävyys',
            ],
            'topic' => [
                0 => 'ananas',
                1 => 'auttaminen',
                2 => 'avioliitto',
                3 => 'baarit',
                4 => 'kauppiaat',
                5 => 'koira',
                6 => 'konsertit',
                7 => 'laiton maahanmuutto',
                8 => 'laivat',
                9 => 'Le Havre',
                10 => 'maahanmuuttajat',
                11 => 'maahanmuuttopolitiikka',
                12 => 'naapuruus',
                13 => 'pakolaiset',
                14 => 'pakolaisleirit',
                15 => 'ihmeparantuminen',
                16 => 'poliisit',
                17 => 'Ranska',
                18 => 'ranskan kieli',
                19 => 'ravintolat',
                20 => 'rock',
                21 => 'sairastuminen',
                22 => 'sairaalat',
                23 => 'satamat',
                24 => 'siirtolaiset',
                25 => 'siirtolaisuus',
                26 => 'sosiaaliset ongelmat',
                27 => 'taudit',
                28 => 'viranomaiset',
                29 => 'vähävaraisuus',
                30 => 'ystävyys',
            ],
            'url' => [],
            'thumbnail' => '',
            'author' => [
                0 => 'Aki Kaurismäki',
                1 => 'Fred Cambier',
                2 => 'Valérie Théry-Hamel',
                3 => 'Gilles Charmant',
                4 => 'Claire Langmann',
                5 => 'Fabienne Vonier',
                6 => 'Reinhard Brundig',
                7 => 'Michel Reilhac',
                8 => 'Rémi Burah',
                9 => 'Meinolf Zurhorst',
                10 => 'Lucas Loubaresse',
                11 => 'Renaud Gast',
                12 => 'Irmeli Debarle',
                13 => 'Malla Hukkanen',
                14 => 'Mika Ailasmäki',
                15 => 'Anne Vahlsten',
                16 => 'Kalle Penttilä',
                17 => 'Ville Väänänen',
                18 => 'Éric Garzena',
                19 => 'Cyril Dupont',
                20 => 'Lazar Abdelkebir',
                21 => 'Benjamin Laurent',
                22 => 'Tero Malmberg',
                23 => 'Konsta Hormia',
                24 => 'Iisakki Hormia',
                25 => 'Olli Pärnänen',
                26 => 'Thomas Pitre',
                27 => 'Pomme Delépine',
                28 => 'Ireneusz (Irek) Spiewak',
                29 => 'Gérard Simonet',
                30 => 'Jean-Claude Guilleman',
                31 => 'Sébastien Gallien',
                32 => 'Pascal Courtinel',
                33 => 'Laurent Thévenot',
                34 => 'Clara Lyonnet',
                35 => 'Diane Wehrly',
                36 => 'Paula Oinonen',
                37 => 'Élise Pradinas',
                38 => 'Elsa Pharaon',
                39 => 'Jean Eninger',
                40 => 'Augustin Werkoff',
                41 => 'Guillaume Moinard',
                42 => 'Marine Longuet',
                43 => 'Pauline Reichenbach',
                44 => 'Yoann Le Gruiec',
                45 => 'Agnès Fanget',
                46 => 'Stéphanie Jossec',
                47 => 'Frank Lesniak',
                48 => 'Frédéric Sibeud',
                49 => 'Thibault Spiral',
                50 => 'Mathieu Raab',
                51 => 'Lucien Lefèbvre',
                52 => 'Éric Morel',
                53 => 'Didier Guéroult',
                54 => 'Gilbert Devaux',
                55 => 'Bruno Joignant',
                56 => 'Thomas Guérin',
                57 => 'Stéphane Livonnen',
                58 => 'Patrice Campelli',
                59 => 'Karl Lemeray',
                60 => 'Jean-Marie Paillette',
                61 => 'Guillaume Macquet',
                62 => 'Patrick Leboucher',
                63 => 'Ève Bruant',
                64 => 'Hanna Hemilä',
                65 => 'Haije Tulokas',
                66 => 'Eevi Kareinen',
                67 => 'Kirsi Hatara',
                68 => 'Heikki Keskinen',
                69 => 'Stéphane Parthenay',
                70 => 'Valérie Farthouat',
                71 => 'Philippe Leconte',
                72 => 'Anne Berjon',
                73 => 'Fanette Martinie',
                74 => 'Louise Lehec',
                75 => 'Karl Baumgartner',
                76 => 'Rainer Teusner',
                77 => 'Viola Fügen',
                78 => 'Camelia Förster',
                79 => 'Frédéric Baroudel',
                80 => 'Catherine Athon',
                81 => 'Frédéric Casnin',
                82 => 'Frédéric Jupin',
                83 => 'Dominique Champel',
                84 => 'Gérard Estival',
                85 => 'Thierry Gazaud',
                86 => 'Franck Tassoul',
                87 => 'Eric Sithavaja',
                88 => 'Jan-Eric Nyström',
                89 => 'Cinéstéréo',
                90 => 'Sputnik Oy',
                91 => 'Ciné Lumières de Paris',
                92 => 'Cinésyl',
                93 => 'Cinéma le studio Le Havre',
                94 => 'Studio Honolulu',
                95 => 'Ptit Bernard Location',
                96 => 'ATP Autocars',
                97 => 'Bus Océane',
                98 => 'Association La Roue en Bois',
                99 => 'Groupe TSF',
                100 => 'Cinéboutique',
                101 => 'Maratier',
                102 => 'Le Vestiaire',
                103 => 'Any d\'Avray',
                104 => 'Rubini & Associés',
                105 => 'Yrittäjäin Fennia',
                106 => 'Paula Oinonen',
            ],
            'author_role' => [
                0 => 'd02',
                1 => 'a99',
                2 => 'a99',
                3 => 'a99',
                4 => 'a99',
                5 => 'a99',
                6 => 'a99',
                7 => 'a99',
                8 => 'a99',
                9 => 'a99',
                10 => 'a99',
                11 => 'a99',
                12 => 'a99',
                13 => 'a99',
                14 => 'a99',
                15 => 'a99',
                16 => 'a99',
                17 => 'a99',
                18 => 'a99',
                19 => 'a99',
                20 => 'a99',
                21 => 'a99',
                22 => 'a99',
                23 => 'a99',
                24 => 'a99',
                25 => 'a99',
                26 => 'a99',
                27 => 'a99',
                28 => 'a99',
                29 => 'a99',
                30 => 'a99',
                31 => 'a99',
                32 => 'a99',
                33 => 'a99',
                34 => 'a99',
                35 => 'a99',
                36 => 'a99',
                37 => 'a99',
                38 => 'a99',
                39 => 'a99',
                40 => 'a99',
                41 => 'a99',
                42 => 'a99',
                43 => 'a99',
                44 => 'a99',
                45 => 'a99',
                46 => 'a99',
                47 => 'a99',
                48 => 'a99',
                49 => 'a99',
                50 => 'a99',
                51 => 'a99',
                52 => 'a99',
                53 => 'a99',
                54 => 'a99',
                55 => 'a99',
                56 => 'a99',
                57 => 'a99',
                58 => 'a99',
                59 => 'a99',
                60 => 'a99',
                61 => 'a99',
                62 => 'a99',
                63 => 'a99',
                64 => 'a99',
                65 => 'a99',
                66 => 'a99',
                67 => 'a99',
                68 => 'a99',
                69 => 'a99',
                70 => 'a99',
                71 => 'a99',
                72 => 'a99',
                73 => 'a99',
                74 => 'a99',
                75 => 'a99',
                76 => 'a99',
                77 => 'a99',
                78 => 'a99',
                79 => 'a99',
                80 => 'a99',
                81 => 'a99',
                82 => 'a99',
                83 => 'a99',
                84 => 'a99',
                85 => 'a99',
                86 => 'a99',
                87 => 'a99',
                88 => 'a99',
                89 => 'a99',
                90 => 'a99',
                91 => 'a99',
                92 => 'a99',
                93 => 'a99',
                94 => 'a99',
                95 => 'a99',
                96 => 'a99',
                97 => 'a99',
                98 => 'a99',
                99 => 'a99',
                100 => 'a99',
                101 => 'a99',
                102 => 'a99',
                103 => 'a99',
                104 => 'a99',
                105 => 'a99',
                106 => 'a99',
            ],
            'author_sort' => 'Aki Kaurismäki',
            'author2' => [
                0 => 'André Wilms',
                1 => 'Kati Outinen',
                2 => 'Jean-Pierre Darroussin',
                3 => 'Blondin Miguel',
                4 => 'Elina Salo',
                5 => 'Evelyne Didi',
                6 => 'Quoc Dung Nguyen',
                7 => 'François Monnié',
                8 => 'Roberto Piazza',
                9 => 'Pierre Étaix',
                10 => 'Jean-Pierre Léaud',
                11 => 'Vincent Lebodo',
                12 => 'Umbañ Uksët',
                13 => 'Patrick Bonnel',
                14 => 'Ilkka Koivula',
                15 => 'Myriam "Mimie" Piazza',
                16 => 'Luce Vigo',
                17 => 'Valérie Caron',
                18 => 'Jérôme Boyer',
                19 => 'Jean-Luc Guion-Firmin',
                20 => 'Pierre Morineau',
                21 => 'Johann Rioux',
                22 => 'Julien Flematti',
                23 => 'Éric Duteil',
                24 => 'Corinne Belet',
                25 => 'Dominique Lepagne',
                26 => 'Anne Lizy',
                27 => 'Pierre Richards',
                28 => 'Loïck Jamet',
                29 => 'Little Bob',
                30 => 'Nico Garotin',
                31 => 'Bertrand Couloume',
                32 => 'Nicolas Noël',
                33 => 'Gilles Mallet',
                34 => 'Gilles Adam',
                35 => 'Patrick Leboucher',
                36 => 'Michel Lacaille',
                37 => 'Stéphane Livonnen',
                38 => 'Arnaud Clément',
                39 => 'Dominique Comont',
                40 => 'Alain Guillot',
                41 => 'Philippe Hubschwerlin',
                42 => 'Franck Durand',
                43 => 'Christian Amyard',
                44 => 'Rudy Amyard',
                45 => 'Brice Augé',
                46 => 'Lucas Loubaresse',
                47 => 'Ireneusz (Irek) Spiewak',
                48 => 'Gilles Charmant',
                49 => 'Mary Berkelmans',
                50 => 'Seluna Lemercier',
                51 => 'Fanette Martinie',
                52 => 'Rémi Pradinas',
                53 => 'Stéphane Parthenay',
                54 => 'Alain Chapelain',
                55 => 'Gilles Adam',
                56 => 'Rachid Bessal',
                57 => 'Oumar Ly',
                58 => 'Emmanuel Ingweiller',
                59 => 'Matthieu Hébert',
                60 => 'Frank Atinault',
                61 => 'Dominique Mare',
                62 => 'Brice Niel',
                63 => 'Alban Rutten',
                64 => 'Franck Rutten',
            ],
            'author2_role' => [
                0 => 'e01',
                1 => 'e01',
                2 => 'e01',
                3 => 'e01',
                4 => 'e01',
                5 => 'e01',
                6 => 'e01',
                7 => 'e01',
                8 => 'e01',
                9 => 'e01',
                10 => 'e01',
                11 => 'e01',
                12 => 'e01',
                13 => 'e01',
                14 => 'e01',
                15 => 'e01',
                16 => 'e01',
                17 => 'e01',
                18 => 'e01',
                19 => 'e01',
                20 => 'e01',
                21 => 'e01',
                22 => 'e01',
                23 => 'e01',
                24 => 'e01',
                25 => 'e01',
                26 => 'e01',
                27 => 'e01',
                28 => 'e01',
                29 => 'e01',
                30 => 'e01',
                31 => 'e01',
                32 => 'e01',
                33 => 'e01',
                34 => 'e01',
                35 => 'e01',
                36 => 'e01',
                37 => 'e01',
                38 => 'e01',
                39 => 'e01',
                40 => 'e01',
                41 => 'e01',
                42 => 'e01',
                43 => 'e01',
                44 => 'e01',
                45 => 'e01',
                46 => 'e01',
                47 => 'e01',
                48 => 'e01',
                49 => 'e01',
                50 => 'e01',
                51 => 'e01',
                52 => 'e01',
                53 => 'e01',
                54 => 'e01',
                55 => 'e01',
                56 => 'e01',
                57 => 'e01',
                58 => 'e01',
                59 => 'e01',
                60 => 'e01',
                61 => 'e01',
                62 => 'e01',
                63 => 'e01',
                64 => 'e01',
            ],
            'author_corporate' => [
                0 => 'Aki Kaurismäki',
                1 => 'Aki Kaurismäki',
                2 => 'Aki Kaurismäki',
                3 => 'Timo Salminen',
                4 => 'Timo Linnasalo',
                5 => 'Tero Malmberg',
                6 => 'Wouter Zoon',
                7 => 'Fred Cambier',
                8 => 'Valérie Théry-Hamel',
                9 => 'Gilles Charmant',
                10 => 'Olli Varja',
                11 => 'Claire Langmann',
                12 => 'Rémi Pradinas',
                13 => 'Mark Lwoff',
                14 => 'Fabienne Vonier',
                15 => 'Reinhard Brundig',
                16 => 'Michel Reilhac',
                17 => 'Rémi Burah',
                18 => 'Meinolf Zurhorst',
                19 => 'Lucas Loubaresse',
                20 => 'Renaud Gast',
                21 => 'Irmeli Debarle',
                22 => 'Malla Hukkanen',
                23 => 'Mika Ailasmäki',
                24 => 'Anne Vahlsten',
                25 => 'Kalle Penttilä',
                26 => 'Ville Väänänen',
                27 => 'Éric Garzena',
                28 => 'Cyril Dupont',
                29 => 'Lazar Abdelkebir',
                30 => 'Benjamin Laurent',
                31 => 'Tero Malmberg',
                32 => 'Konsta Hormia',
                33 => 'Iisakki Hormia',
                34 => 'Olli Pärnänen',
                35 => 'Thomas Pitre',
                36 => 'Pomme Delépine',
                37 => 'Ireneusz (Irek) Spiewak',
                38 => 'Gérard Simonet',
                39 => 'Jean-Claude Guilleman',
                40 => 'Sébastien Gallien',
                41 => 'Pascal Courtinel',
                42 => 'Laurent Thévenot',
                43 => 'Clara Lyonnet',
                44 => 'Diane Wehrly',
                45 => 'Paula Oinonen',
                46 => 'Élise Pradinas',
                47 => 'Elsa Pharaon',
                48 => 'Jean Eninger',
                49 => 'Augustin Werkoff',
                50 => 'Guillaume Moinard',
                51 => 'Marine Longuet',
                52 => 'Pauline Reichenbach',
                53 => 'Yoann Le Gruiec',
                54 => 'Agnès Fanget',
                55 => 'Stéphanie Jossec',
                56 => 'Frank Lesniak',
                57 => 'Frédéric Sibeud',
                58 => 'Thibault Spiral',
                59 => 'Mathieu Raab',
                60 => 'Lucien Lefèbvre',
                61 => 'Éric Morel',
                62 => 'Didier Guéroult',
                63 => 'Gilbert Devaux',
                64 => 'Bruno Joignant',
                65 => 'Thomas Guérin',
                66 => 'Stéphane Livonnen',
                67 => 'Patrice Campelli',
                68 => 'Karl Lemeray',
                69 => 'Jean-Marie Paillette',
                70 => 'Guillaume Macquet',
                71 => 'Patrick Leboucher',
                72 => 'Irmeli Debarle',
                73 => 'Mikko Lyytikäinen',
                74 => 'Ève Bruant',
                75 => 'Hanna Hemilä',
                76 => 'Haije Tulokas',
                77 => 'Eevi Kareinen',
                78 => 'Kirsi Hatara',
                79 => 'Heikki Keskinen',
                80 => 'Stéphane Parthenay',
                81 => 'Valérie Farthouat',
                82 => 'Philippe Leconte',
                83 => 'Anne Berjon',
                84 => 'Fanette Martinie',
                85 => 'Louise Lehec',
                86 => 'Karl Baumgartner',
                87 => 'Rainer Teusner',
                88 => 'Viola Fügen',
                89 => 'Camelia Förster',
                90 => 'Frédéric Baroudel',
                91 => 'Catherine Athon',
                92 => 'Frédéric Casnin',
                93 => 'Frédéric Jupin',
                94 => 'Dominique Champel',
                95 => 'Gérard Estival',
                96 => 'Thierry Gazaud',
                97 => 'Franck Tassoul',
                98 => 'Eric Sithavaja',
                99 => 'Jan-Eric Nyström',
                100 => 'Cinéstéréo',
                101 => 'Sputnik Oy',
                102 => 'Ciné Lumières de Paris',
                103 => 'Cinésyl',
                104 => 'Cinéma le studio Le Havre',
                105 => 'Studio Honolulu',
                106 => 'Ptit Bernard Location',
                107 => 'ATP Autocars',
                108 => 'Bus Océane',
                109 => 'Association La Roue en Bois',
                110 => 'Groupe TSF',
                111 => 'Cinéboutique',
                112 => 'Maratier',
                113 => 'Le Vestiaire',
                114 => 'Any d\'Avray',
                115 => 'Rubini & Associés',
                116 => 'Yrittäjäin Fennia',
                117 => 'André Wilms',
                118 => 'Kati Outinen',
                119 => 'Jean-Pierre Darroussin',
                120 => 'Blondin Miguel',
                121 => 'Elina Salo',
                122 => 'Evelyne Didi',
                123 => 'Quoc Dung Nguyen',
                124 => 'François Monnié',
                125 => 'Roberto Piazza',
                126 => 'Pierre Étaix',
                127 => 'Jean-Pierre Léaud',
                128 => 'Vincent Lebodo',
                129 => 'Umbañ Uksët',
                130 => 'Patrick Bonnel',
                131 => 'Ilkka Koivula',
                132 => 'Myriam "Mimie" Piazza',
                133 => 'Luce Vigo',
                134 => 'Valérie Caron',
                135 => 'Jérôme Boyer',
                136 => 'Jean-Luc Guion-Firmin',
                137 => 'Pierre Morineau',
                138 => 'Johann Rioux',
                139 => 'Julien Flematti',
                140 => 'Éric Duteil',
                141 => 'Corinne Belet',
                142 => 'Dominique Lepagne',
                143 => 'Anne Lizy',
                144 => 'Pierre Richards',
                145 => 'Loïck Jamet',
                146 => 'Little Bob',
                147 => 'Nico Garotin',
                148 => 'Bertrand Couloume',
                149 => 'Nicolas Noël',
                150 => 'Gilles Mallet',
                151 => 'Gilles Adam',
                152 => 'Patrick Leboucher',
                153 => 'Michel Lacaille',
                154 => 'Stéphane Livonnen',
                155 => 'Arnaud Clément',
                156 => 'Dominique Comont',
                157 => 'Alain Guillot',
                158 => 'Philippe Hubschwerlin',
                159 => 'Franck Durand',
                160 => 'Christian Amyard',
                161 => 'Rudy Amyard',
                162 => 'Brice Augé',
                163 => 'Lucas Loubaresse',
                164 => 'Ireneusz (Irek) Spiewak',
                165 => 'Gilles Charmant',
                166 => 'Mary Berkelmans',
                167 => 'Seluna Lemercier',
                168 => 'Fanette Martinie',
                169 => 'Rémi Pradinas',
                170 => 'Stéphane Parthenay',
                171 => 'Alain Chapelain',
                172 => 'Gilles Adam',
                173 => 'Rachid Bessal',
                174 => 'Oumar Ly',
                175 => 'Emmanuel Ingweiller',
                176 => 'Matthieu Hébert',
                177 => 'Frank Atinault',
                178 => 'Dominique Mare',
                179 => 'Brice Niel',
                180 => 'Alban Rutten',
                181 => 'Franck Rutten',
                182 => 'Sputnik Oy',
                183 => 'Pyramide Productions',
                184 => 'Pandora Filmproduktion GmbH',
                185 => 'Arte France Cinéma',
                186 => 'ZDF / ARTE',
                187 => 'Suomen elokuvasäätiö SES',
                188 => 'Canal+',
                189 => 'Nordisk Film & TV Fond NFTF',
                190 => 'Le Centre National du Cinéma et de l\'Image Animée',
                191 => 'YLE Yhteistuotannot',
                192 => 'CinéCinéma',
                193 => 'Arte France',
                194 => 'Arte G.E.I.E.',
                195 => 'Suomen elokuvasäätiö SES',
                196 => 'Suomen elokuvasäätiö SES',
                197 => 'Suomen elokuvasäätiö SES',
                198 => 'Future Film Oy',
                199 => 'Future Film Oy',
                200 => 'The Match Factory GmbH',
                201 => 'Paula Oinonen',
            ],
            'author_corporate_role' => [
                0 => 'd02',
                1 => 'aus',
                2 => 'fmp',
                3 => 'cng',
                4 => 'flm',
                5 => 'sds',
                6 => 'std',
                7 => 'a99',
                8 => 'a99',
                9 => 'a99',
                10 => 'lgd',
                11 => 'a99',
                12 => 'pmn',
                13 => 'pmn',
                14 => 'a99',
                15 => 'a99',
                16 => 'a99',
                17 => 'a99',
                18 => 'a99',
                19 => 'a99',
                20 => 'a99',
                21 => 'a99',
                22 => 'a99',
                23 => 'a99',
                24 => 'a99',
                25 => 'a99',
                26 => 'a99',
                27 => 'a99',
                28 => 'a99',
                29 => 'a99',
                30 => 'a99',
                31 => 'a99',
                32 => 'a99',
                33 => 'a99',
                34 => 'a99',
                35 => 'a99',
                36 => 'a99',
                37 => 'a99',
                38 => 'a99',
                39 => 'a99',
                40 => 'a99',
                41 => 'a99',
                42 => 'a99',
                43 => 'a99',
                44 => 'a99',
                45 => 'a99',
                46 => 'a99',
                47 => 'a99',
                48 => 'a99',
                49 => 'a99',
                50 => 'a99',
                51 => 'a99',
                52 => 'a99',
                53 => 'a99',
                54 => 'a99',
                55 => 'a99',
                56 => 'a99',
                57 => 'a99',
                58 => 'a99',
                59 => 'a99',
                60 => 'a99',
                61 => 'a99',
                62 => 'a99',
                63 => 'a99',
                64 => 'a99',
                65 => 'a99',
                66 => 'a99',
                67 => 'a99',
                68 => 'a99',
                69 => 'a99',
                70 => 'a99',
                71 => 'a99',
                72 => 'trl',
                73 => 'trl',
                74 => 'a99',
                75 => 'a99',
                76 => 'a99',
                77 => 'a99',
                78 => 'a99',
                79 => 'a99',
                80 => 'a99',
                81 => 'a99',
                82 => 'a99',
                83 => 'a99',
                84 => 'a99',
                85 => 'a99',
                86 => 'a99',
                87 => 'a99',
                88 => 'a99',
                89 => 'a99',
                90 => 'a99',
                91 => 'a99',
                92 => 'a99',
                93 => 'a99',
                94 => 'a99',
                95 => 'a99',
                96 => 'a99',
                97 => 'a99',
                98 => 'a99',
                99 => 'a99',
                100 => 'a99',
                101 => 'a99',
                102 => 'a99',
                103 => 'a99',
                104 => 'a99',
                105 => 'a99',
                106 => 'a99',
                107 => 'a99',
                108 => 'a99',
                109 => 'a99',
                110 => 'a99',
                111 => 'a99',
                112 => 'a99',
                113 => 'a99',
                114 => 'a99',
                115 => 'a99',
                116 => 'a99',
                117 => 'e01',
                118 => 'e01',
                119 => 'e01',
                120 => 'e01',
                121 => 'e01',
                122 => 'e01',
                123 => 'e01',
                124 => 'e01',
                125 => 'e01',
                126 => 'e01',
                127 => 'e01',
                128 => 'e01',
                129 => 'e01',
                130 => 'e01',
                131 => 'e01',
                132 => 'e01',
                133 => 'e01',
                134 => 'e01',
                135 => 'e01',
                136 => 'e01',
                137 => 'e01',
                138 => 'e01',
                139 => 'e01',
                140 => 'e01',
                141 => 'e01',
                142 => 'e01',
                143 => 'e01',
                144 => 'e01',
                145 => 'e01',
                146 => 'e01',
                147 => 'e01',
                148 => 'e01',
                149 => 'e01',
                150 => 'e01',
                151 => 'e01',
                152 => 'e01',
                153 => 'e01',
                154 => 'e01',
                155 => 'e01',
                156 => 'e01',
                157 => 'e01',
                158 => 'e01',
                159 => 'e01',
                160 => 'e01',
                161 => 'e01',
                162 => 'e01',
                163 => 'e01',
                164 => 'e01',
                165 => 'e01',
                166 => 'e01',
                167 => 'e01',
                168 => 'e01',
                169 => 'e01',
                170 => 'e01',
                171 => 'e01',
                172 => 'e01',
                173 => 'e01',
                174 => 'e01',
                175 => 'e01',
                176 => 'e01',
                177 => 'e01',
                178 => 'e01',
                179 => 'e01',
                180 => 'e01',
                181 => 'e01',
                182 => 'e10',
                183 => 'e10',
                184 => 'e10',
                185 => 'e10',
                186 => 'e10',
                187 => 'fnd',
                188 => 'fnd',
                189 => 'fnd',
                190 => 'fnd',
                191 => 'fnd',
                192 => 'fnd',
                193 => 'fnd',
                194 => 'fnd',
                195 => 'fnd',
                196 => 'fnd',
                197 => 'fnd',
                198 => 'fds',
                199 => 'fds',
                200 => 'fds',
                201 => 'a99',
            ],
            'geographic_facet' => [
                0 => 'Suomi',
                1 => 'Ranska',
                2 => 'Saksa',
            ],
            'geographic' => [
                0 => 'Suomi',
                1 => 'Ranska',
                2 => 'Saksa',
            ],
            'genre_facet' => [
            ],
            'genre' => [
            ],
            'format' => 'MotionPicture',
            'publisher' => [
            ],
            'allfields' => [
                0 => 'Le Havre',
                1 => 'Le Havre',
                2 => 'Le Havre',
                3 => 'Mannen från Le Havre',
                4 => 'Le Havre',
                5 => 'Le Havre',
                6 => 'Le Havre',
                7 => 'El Havre',
                8 => 'El Puerto',
                9 => 'El Puerto',
                10 => 'Le Havre: el puerto de la esperanza',
                11 => 'Hof mivtahim',
                12 => 'Miracolo a Le Havre',
                13 => 'To limani tis Havris',
                14 => 'Havras',
                15 => 'Le Havre',
                16 => 'O Porto',
                17 => 'Czlowiek z Hawru',
                18 => 'Miraklet i Le Havre',
                19 => 'Umut Limani',
                20 => 'Kikötői történet',
                21 => 'Gavr',
                22 => 'Le Havre: Sadamalinn',
                23 => 'Le Havre',
                24 => 'Suomi',
                25 => 'Ranska',
                26 => 'Saksa',
                27 => '2011',
                28 => 'Aki Kaurismäki',
                29 => 'Aki Kaurismäki',
                30 => 'Aki Kaurismäki',
                31 => 'Timo Salminen',
                32 => 'Timo Linnasalo',
                33 => 'Tero Malmberg',
                34 => 'Wouter Zoon',
                35 => 'Fred Cambier',
                36 => 'Valérie Théry-Hamel',
                37 => 'Gilles Charmant',
                38 => 'Olli Varja',
                39 => 'Claire Langmann',
                40 => 'Rémi Pradinas',
                41 => 'Mark Lwoff',
                42 => 'Fabienne Vonier',
                43 => 'Reinhard Brundig',
                44 => 'Michel Reilhac',
                45 => 'Rémi Burah',
                46 => 'Meinolf Zurhorst',
                47 => 'Lucas Loubaresse',
                48 => 'Renaud Gast',
                49 => 'Irmeli Debarle',
                50 => 'Malla Hukkanen',
                51 => 'Mika Ailasmäki',
                52 => 'Anne Vahlsten',
                53 => 'Kalle Penttilä',
                54 => 'Ville Väänänen',
                55 => 'Éric Garzena',
                56 => 'Cyril Dupont',
                57 => 'Lazar Abdelkebir',
                58 => 'Benjamin Laurent',
                59 => 'Tero Malmberg',
                60 => 'Konsta Hormia',
                61 => 'Iisakki Hormia',
                62 => 'Olli Pärnänen',
                63 => 'Thomas Pitre',
                64 => 'Pomme Delépine',
                65 => 'Ireneusz (Irek) Spiewak',
                66 => 'Gérard Simonet',
                67 => 'Jean-Claude Guilleman',
                68 => 'Sébastien Gallien',
                69 => 'Pascal Courtinel',
                70 => 'Laurent Thévenot',
                71 => 'Clara Lyonnet',
                72 => 'Diane Wehrly',
                73 => 'Paula Oinonen',
                74 => 'Élise Pradinas',
                75 => 'Elsa Pharaon',
                76 => 'Jean Eninger',
                77 => 'Augustin Werkoff',
                78 => 'Guillaume Moinard',
                79 => 'Marine Longuet',
                80 => 'Pauline Reichenbach',
                81 => 'Yoann Le Gruiec',
                82 => 'Agnès Fanget',
                83 => 'Stéphanie Jossec',
                84 => 'Frank Lesniak',
                85 => 'Frédéric Sibeud',
                86 => 'Thibault Spiral',
                87 => 'Mathieu Raab',
                88 => 'Lucien Lefèbvre',
                89 => 'Éric Morel',
                90 => 'Didier Guéroult',
                91 => 'Gilbert Devaux',
                92 => 'Bruno Joignant',
                93 => 'Thomas Guérin',
                94 => 'Stéphane Livonnen',
                95 => 'Patrice Campelli',
                96 => 'Karl Lemeray',
                97 => 'Jean-Marie Paillette',
                98 => 'Guillaume Macquet',
                99 => 'Patrick Leboucher',
                100 => 'Irmeli Debarle',
                101 => 'Mikko Lyytikäinen',
                102 => 'Ève Bruant',
                103 => 'Hanna Hemilä',
                104 => 'Haije Tulokas',
                105 => 'Eevi Kareinen',
                106 => 'Kirsi Hatara',
                107 => 'Heikki Keskinen',
                108 => 'Stéphane Parthenay',
                109 => 'Valérie Farthouat',
                110 => 'Philippe Leconte',
                111 => 'Anne Berjon',
                112 => 'Fanette Martinie',
                113 => 'Louise Lehec',
                114 => 'Karl Baumgartner',
                115 => 'Rainer Teusner',
                116 => 'Viola Fügen',
                117 => 'Camelia Förster',
                118 => 'Frédéric Baroudel',
                119 => 'Catherine Athon',
                120 => 'Frédéric Casnin',
                121 => 'Frédéric Jupin',
                122 => 'Dominique Champel',
                123 => 'Gérard Estival',
                124 => 'Thierry Gazaud',
                125 => 'Franck Tassoul',
                126 => 'Eric Sithavaja',
                127 => 'Jan-Eric Nyström',
                128 => 'Cinéstéréo',
                129 => 'Sputnik Oy',
                130 => 'Ciné Lumières de Paris',
                131 => 'Cinésyl',
                132 => 'Cinéma le studio Le Havre',
                133 => 'Studio Honolulu',
                134 => 'Ptit Bernard Location',
                135 => 'ATP Autocars',
                136 => 'Bus Océane',
                137 => 'Association La Roue en Bois',
                138 => 'Groupe TSF',
                139 => 'Cinéboutique',
                140 => 'Maratier',
                141 => 'Le Vestiaire',
                142 => 'Any d\'Avray',
                143 => 'Rubini & Associés',
                144 => 'Yrittäjäin Fennia',
                145 => 'André Wilms',
                146 => 'Kati Outinen',
                147 => 'Jean-Pierre Darroussin',
                148 => 'Blondin Miguel',
                149 => 'Elina Salo',
                150 => 'Evelyne Didi',
                151 => 'Quoc Dung Nguyen',
                152 => 'François Monnié',
                153 => 'Roberto Piazza',
                154 => 'Pierre Étaix',
                155 => 'Jean-Pierre Léaud',
                156 => 'Vincent Lebodo',
                157 => 'Umbañ Uksët',
                158 => 'Patrick Bonnel',
                159 => 'Ilkka Koivula',
                160 => 'Myriam "Mimie" Piazza',
                161 => 'Luce Vigo',
                162 => 'Valérie Caron',
                163 => 'Jérôme Boyer',
                164 => 'Jean-Luc Guion-Firmin',
                165 => 'Pierre Morineau',
                166 => 'Johann Rioux',
                167 => 'Julien Flematti',
                168 => 'Éric Duteil',
                169 => 'Corinne Belet',
                170 => 'Dominique Lepagne',
                171 => 'Anne Lizy',
                172 => 'Pierre Richards',
                173 => 'Loïck Jamet',
                174 => 'Little Bob',
                175 => 'Nico Garotin',
                176 => 'Bertrand Couloume',
                177 => 'Nicolas Noël',
                178 => 'Gilles Mallet',
                179 => 'Gilles Adam',
                180 => 'Patrick Leboucher',
                181 => 'Michel Lacaille',
                182 => 'Stéphane Livonnen',
                183 => 'Arnaud Clément',
                184 => 'Dominique Comont',
                185 => 'Alain Guillot',
                186 => 'Philippe Hubschwerlin',
                187 => 'Franck Durand',
                188 => 'Christian Amyard',
                189 => 'Rudy Amyard',
                190 => 'Brice Augé',
                191 => 'Lucas Loubaresse',
                192 => 'Ireneusz (Irek) Spiewak',
                193 => 'Gilles Charmant',
                194 => 'Mary Berkelmans',
                195 => 'Seluna Lemercier',
                196 => 'Fanette Martinie',
                197 => 'Rémi Pradinas',
                198 => 'Stéphane Parthenay',
                199 => 'Alain Chapelain',
                200 => 'Gilles Adam',
                201 => 'Rachid Bessal',
                202 => 'Oumar Ly',
                203 => 'Emmanuel Ingweiller',
                204 => 'Matthieu Hébert',
                205 => 'Frank Atinault',
                206 => 'Dominique Mare',
                207 => 'Brice Niel',
                208 => 'Alban Rutten',
                209 => 'Franck Rutten',
                210 => 'Sputnik Oy',
                211 => 'Pyramide Productions',
                212 => 'Pandora Filmproduktion GmbH',
                213 => 'Arte France Cinéma',
                214 => 'ZDF / ARTE',
                215 => 'Suomen elokuvasäätiö SES',
                216 => 'Canal+',
                217 => 'Nordisk Film & TV Fond NFTF',
                218 => 'Le Centre National du Cinéma et de l\'Image Animée',
                219 => 'YLE Yhteistuotannot',
                220 => 'CinéCinéma',
                221 => 'Arte France',
                222 => 'Arte G.E.I.E',
                223 => 'Suomen elokuvasäätiö SES',
                224 => 'Suomen elokuvasäätiö SES',
                225 => 'Suomen elokuvasäätiö SES',
                226 => 'Future Film Oy',
                227 => 'Future Film Oy',
                228 => 'The Match Factory GmbH',
                229 => 'Paula Oinonen',
                230 => 'ananas',
                231 => 'auttaminen',
                232 => 'avioliitto',
                233 => 'baarit',
                234 => 'kauppiaat',
                235 => 'koira',
                236 => 'konsertit',
                237 => 'laiton maahanmuutto',
                238 => 'laivat',
                239 => 'Le Havre',
                240 => 'maahanmuuttajat',
                241 => 'maahanmuuttopolitiikka',
                242 => 'naapuruus',
                243 => 'pakolaiset',
                244 => 'pakolaisleirit',
                245 => 'ihmeparantuminen',
                246 => 'poliisit',
                247 => 'Ranska',
                248 => 'ranskan kieli',
                249 => 'ravintolat',
                250 => 'rock',
                251 => 'sairastuminen',
                252 => 'sairaalat',
                253 => 'satamat',
                254 => 'siirtolaiset',
                255 => 'siirtolaisuus',
                256 => 'sosiaaliset ongelmat',
                257 => 'taudit',
                258 => 'viranomaiset',
                259 => 'vähävaraisuus',
                260 => 'ystävyys',
                261 => 'Cannesin elokuvajuhlat, Cannes, Ranska 2011: FIPRESCI:n'
                    . ' palkinto; Palme Dog: Laika; kirkollisen tuomariston'
                    . ' erikoispalkinto.<br />Filmfest München, München, Saksa 2011:'
                    . ' paras ulkomainen elokuva (ARRI Award).<br />St. Petersburg'
                    . ' International Film Festival “Kinoforum”, Pietari, Venäjä'
                    . ' 2011: yleisöpalkinto.<br />Festival del film Locarno,'
                    . ' Locarno, Sveitsi 2011: Premio Boccalino -kriitikkopalkinto:'
                    . ' paras naisnäyttelijä: Kati Outinen.<br />Reykjavik'
                    . ' International Film Festival, Reykjavik, Islanti 2011:'
                    . ' yleisöpalkinto.<br />Chicago International Film Festival,'
                    . ' Chicago (IL), Yhdysvallat 2011: pääpalkinto (Gold Hugo)'
                    . ' kansainvälisten elokuvien sarjassa.<br />National Board of'
                    . ' Review Awards, Yhdysvallat 2011: palkinto Top 5 Foreign'
                    . ' Language Films -sarjassa.<br />Prix Louis-Delluc, Ranska'
                    . ' 2011.<br /><br />Jussit 2012: paras elokuva; paras ohjaus:'
                    . ' Aki Kaurismäki; paras käsikirjoitus: Aki Kaurismäki; paras'
                    . ' kuvaus: Timo Salminen; paras leikkaus: Timo Linnasalo; paras'
                    . ' naissivuosa: Elina Salo.<br />Viitasaaren elokuvaviikko'
                    . ' 2012: Humanismin käsi: Aki Kaurismäki',
                262 => 'Aki Kaurismäen ohjaama, tuottama ja käsikirjoittama <i>Le'
                    . ' Havre</i> (2011) kertoo ranskalaisesta kengänkiillottajasta,'
                    . ' Marcel Marxista (André Wilms), joka haluaa auttaa nuorta'
                    . ' laitonta afrikkalaissiirtolaista, Idrissaa (Blondin Miguel).'
                    . ' Marcel saa hankkeessaan tukea naapurustoltaan, mutta samaan'
                    . ' aikaan huolta tuottaa Arletty-vaimon (Kati Outinen)'
                    . ' sairastuminen',
                263 => 'Marcel Marx, entinen kirjailija, elää Ranskassa Le Havressa'
                    . ' vaatimattomasti kengänkiillottajana vaimonsa Arlettyn'
                    . ' kanssa. Satamakaupungissa kuohuu: tavarakontista löydetään'
                    . ' laittomia afrikkalaissiirtolaisia. Eräs pakolaisista,'
                    . ' nuori Idrissa, juoksee karkuun poliiseilta. Seuraavana'
                    . ' päivänä Marcel löytää pojan satamasta. Komisario Monet'
                    . ' osuu paikalle, mutta Marcel ei ilmianna karkulaista. Yön'
                    . ' turvin mies vie ruokaa Idrissalle ja laittaa paperipussiin'
                    . ' myös rahaa.<br /><br />Kotona Laika-koira on levoton:'
                    . ' Arletty ei voi hyvin. Naapuri, Yvette, vie pariskunnan'
                    . ' sairaalaan, mutta tohtori Becker kehottaa Marcelia palaamaan'
                    . ' kotiin. Marcel löytää Idrissan vajastaan. Poika on tullut'
                    . ' maksamaan velkansa ja kertoo haluavansa Lontooseen äitinsä'
                    . ' luo. Marcel päättää auttaa ja antaa pojalle piilopaikan.'
                    . '<br /><br />Arletty kuulee tohtorilta, että hänen elämänsä on'
                    . ' ihmeen varassa. ”Ihmeitä ei tapahdu minun korttelissani”,'
                    . ' nainen tuumaa ja kieltää kertomasta tilansa vakavuutta'
                    . ' puolisolleen. Marcelilla on huolta myös Idrissasta, mutta'
                    . ' koko hänen naapurustonsa on suureksi avuksi. Ainoastaan'
                    . ' vastapäisen talon vanhus soittaa poliisille'
                    . ' siirtolaishavainnostaan. Komisario Monet kehottaa Marcelia'
                    . ' varomaan naapuriaan.<br /> <br />Marcel ryhtyy selvittämään,'
                    . ' miten Idrissa löytäisi äitinsä Lontoosta. Hän jättää pojan'
                    . ' Yvetten hoitoon ja lähtee Calais’hen tapaamaan'
                    . ' pakolaisleirillä olevaa Idrissan isoisää. Pakolaiskeskuksen'
                    . ' maahanmuuttoviranomaisia Marcel hämmentää väittämällä'
                    . ' kivenkovaa olevansa sukua, ”perheen albiino”. Isoisä antaa'
                    . ' matkaohjeet ja osoitteen. Sillä välin Idrissa karkaa Yvetten'
                    . ' luota kiillottamaan kenkiä asemalle. Marcelin naapuri'
                    . ' yrittää ottaa pojan kiinni, mutta Marcelin työtoveri Chang'
                    . ' tulee hätiin ja poika pääsee jälleen turvaan. <br /><br />'
                    . 'Sairaalan vierastunnilla Arletty valehtelee tilastaan'
                    . ' aviomiehelleen. Hän kieltää hoitojensa vuoksi Marcelia'
                    . ' tulemasta tervehtimään ja käskee tätä palaamaan kahden'
                    . ' viikon päästä ja tuomaan hänen keltaisen leninkinsä. Yvetten'
                    . ' ja kapakoitsija Clairen kanssa Arletty ei vaihda kuulumisia'
                    . ' sen pirteämmin, vaan on huonokuntoinen ja väsynyt.<br />'
                    . '<br />Komisario Monet tekee tutkimuksiaan. Hän tarkkailee'
                    . ' Marcelin liikkeitä ja kyselee vihanneskauppiaalta tietoja'
                    . ' miehestä. Ananas muassaan hän menee myös Clairen baariin.'
                    . ' Claire häätää asiakkaat pois ja istahtaa juttusille Monet’n'
                    . ' kanssa. He ovat vanhoja tuttuja; komisario toimitti Clairen'
                    . ' aviomiesvainaan telkien taa.<br /><br />Marcel sopii'
                    . ' satamassa Idrissan pakojärjestelyistä. Venekyytiin tarvitaan'
                    . ' 3000 euroa. Ystävät ehdottavat, että Marcel järjestäisi'
                    . ' muodikkaan tukikonsertin. Kun Marcel saa hierottua'
                    . ' paikallisen rock-legendan Little Bobin ja tämän kipakan'
                    . ' vaimon Mimien välille sovinnon, voidaan konsertti järjestää.'
                    . ' Marcel itse erehtyy päivästä ja joutuu lähettämään Idrissan'
                    . ' sairaalaan Arlettyn mekkoa viemään. Idrissa kehottaa'
                    . ' Arlettya paranemaan pian, sillä Marcel ei pärjää ilman'
                    . ' vaimoaan.<br /><br />Little Bobin konsertti on menestys, ja'
                    . ' Marcel saa tarvittavan summan kasaan, ennen kuin poliisit'
                    . ' saapuvat. Tilanne kotikulmilla käy kuumaksi, ja Monet'
                    . ' varoittaa Marcelia viime tipassa. Poliisit rynnivät'
                    . ' kengänkiillottajan asuntoon, mutta Idrissa pakenee'
                    . ' ikkunasta. Hänet kuskataan satamaan vihanneskärryissä.'
                    . ' Poika saadaan veneeseen ja raha-asiat hoidettua, kun'
                    . ' poliisit saartavat sataman. Monet saapuu hätiin ja on'
                    . ' tarkistavinaan laivan, jossa Marcel ja Idrissa ovat. Hän ei'
                    . ' ilmianna pakolaista, vaan poika pääsee matkaan. Marcel ja'
                    . ' Monet ystävystyvät.<br /><br />Sairaalassa on tapahtunut'
                    . ' ihme: Arletty on toipunut ja pariskunta pääsee palaamaan'
                    . ' kotiin. Kotona kirsikkapuu kukkii.<br /><br /><i>Teksti:'
                    . ' Suomen kansallisfilmografia / Tytti Rantanen 2016</i>',
                264 => 'Marcel Marx, a former author and a well-known bohemian, has'
                    . ' retreated into a voluntary exile in the port city of Le'
                    . ' Havre, where he feels he has reached a closer rapport with'
                    . ' the people serving them in the occupation of the honourable,'
                    . ' but not too profitable, of a shoe-shiner. He has buried his'
                    . ' dreams of a literary breakthrough and lives happily within'
                    . ' the triangle of his favourite bar, his work, and his wife'
                    . ' Arletty, when fate suddenly throws in his path an underage'
                    . ' immigrant refugee from the darkest Africa.<br /><br />As'
                    . ' Arletty at the same time gets seriously ill and is'
                    . ' bedridden, Marcel once more has to rise against the cold'
                    . ' wall of human indifference with his only weapon of innate'
                    . ' optimism and the unwavering solidarity of the people of his'
                    . ' quartier, but against him stands the whole blind machinery'
                    . ' of the Western constitutionally governed state, this time'
                    . ' represented by the dragnet of the police, moment by moment'
                    . ' drawing closer around the refugee boy.<br /><br />It\'s time'
                    . ' for Marcel to polish his shoes and reveal his teeth',
            ],
        ];

        $this->compareArray($expected, $fields, 'toSolrArray');

        $keys = $record->getWorkIdentificationData();

        $expected = [
            [
                'authors' => [
                    0 => [
                        'type' => 'author',
                        'value' => 'Kaurismäki, Aki',
                    ],
                ],
                'authorsAltScript' => [
                ],
                'titles' => [
                    0 => [
                        'type' => 'title',
                        'value' => 'Havre',
                    ],
                    1 => [
                        'type' => 'title',
                        'value' => 'Le Havre',
                    ],
                ],
                'titlesAltScript' => [
                ],
            ]
        ];

        $this->compareArray($expected, $keys, 'getWorkIdentificationData');
    }
}
