<?php
/**
 * FORWARD Record Driver Test Class
 *
 * PHP version 7
 *
 * Copyright (C) The National Library of Finland 2020.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category DataManagement
 * @package  RecordManager
 * @author   Ere Maijala <ere.maijala@helsinki.fi>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://github.com/NatLibFi/RecordManager
 */
namespace RecordManagerTest\Base\Record;

use RecordManager\Base\Record\Forward;

/**
 * FORWARD Record Driver Test Class
 *
 * @category DataManagement
 * @package  RecordManager
 * @author   Ere Maijala <ere.maijala@helsinki.fi>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://github.com/NatLibFi/RecordManager
 */
class ForwardTest extends RecordTest
{
    /**
     * Test FORWARD Record handling
     *
     * @return void
     */
    public function testForward1()
    {
        $record = $this->createRecord(Forward::class, 'forward1.xml');
        $fields = $record->toSolrArray();
        unset($fields['fullrecord']);

        $expected = [
            'record_format' => 'forward',
            'ctrlnum' => 'elonet_elokuva_1511500',
            'publishDate' => '2011',
            'title' => 'Le Havre',
            'title_alt' => [
                0 => 'Mannen från Le Havre',
                1 => 'El Havre',
                2 => 'El Puerto',
                3 => 'El Puerto',
                4 => 'Le Havre: el puerto de la esperanza',
                5 => 'Hof mivtahim',
                6 => 'Miracolo a Le Havre',
                7 => 'To limani tis Havris',
                8 => 'Havras',
                9 => 'O Porto',
                10 => 'Czlowiek z Hawru',
                11 => 'Miraklet i Le Havre',
                12 => 'Umut Limani',
                13 => 'Kikötői történet',
                14 => 'Gavr',
                15 => 'Le Havre: Sadamalinn',
            ],
            'title_full' => 'Le Havre',
            'title_short' => 'Le Havre',
            'title_sort' => 'havre',
            'description' => 'Marcel Marx, a former author and a well-known'
                . ' bohemian, has retreated into a voluntary exile in the port city'
                . ' of Le Havre[...] Marcel Marx, entinen kirjailija, elää Ranskassa'
                . ' Le Havressa vaatimattomasti kengänkiillottajana vaimonsa'
                . ' Arlettyn kanssa[...]',
            'topic_facet' => [
                0 => 'ananas',
                1 => 'auttaminen',
                2 => 'avioliitto',
                3 => 'baarit',
                4 => 'kauppiaat',
                5 => 'koira',
                6 => 'konsertit',
                7 => 'laiton maahanmuutto',
                8 => 'laivat',
                9 => 'Le Havre',
                10 => 'maahanmuuttajat',
                11 => 'maahanmuuttopolitiikka',
                12 => 'naapuruus',
                13 => 'pakolaiset',
                14 => 'pakolaisleirit',
                15 => 'ihmeparantuminen',
                16 => 'poliisit',
                17 => 'Ranska',
                18 => 'ranskan kieli',
                19 => 'ravintolat',
                20 => 'rock',
                21 => 'sairastuminen',
                22 => 'sairaalat',
                23 => 'satamat',
                24 => 'siirtolaiset',
                25 => 'siirtolaisuus',
                26 => 'sosiaaliset ongelmat',
                27 => 'taudit',
                28 => 'viranomaiset',
                29 => 'vähävaraisuus',
                30 => 'ystävyys',
            ],
            'topic' => [
                0 => 'ananas',
                1 => 'auttaminen',
                2 => 'avioliitto',
                3 => 'baarit',
                4 => 'kauppiaat',
                5 => 'koira',
                6 => 'konsertit',
                7 => 'laiton maahanmuutto',
                8 => 'laivat',
                9 => 'Le Havre',
                10 => 'maahanmuuttajat',
                11 => 'maahanmuuttopolitiikka',
                12 => 'naapuruus',
                13 => 'pakolaiset',
                14 => 'pakolaisleirit',
                15 => 'ihmeparantuminen',
                16 => 'poliisit',
                17 => 'Ranska',
                18 => 'ranskan kieli',
                19 => 'ravintolat',
                20 => 'rock',
                21 => 'sairastuminen',
                22 => 'sairaalat',
                23 => 'satamat',
                24 => 'siirtolaiset',
                25 => 'siirtolaisuus',
                26 => 'sosiaaliset ongelmat',
                27 => 'taudit',
                28 => 'viranomaiset',
                29 => 'vähävaraisuus',
                30 => 'ystävyys',
            ],
            'url' => [],
            'thumbnail' => '',
            'author' => [
                0 => 'Aki Kaurismäki',
                1 => 'Fred Cambier',
                2 => 'Valérie Théry-Hamel',
                3 => 'Gilles Charmant',
                4 => 'Claire Langmann',
                5 => 'Fabienne Vonier',
                6 => 'Reinhard Brundig',
                7 => 'Michel Reilhac',
                8 => 'Rémi Burah',
                9 => 'Meinolf Zurhorst',
                10 => 'Lucas Loubaresse',
                11 => 'Renaud Gast',
                12 => 'Irmeli Debarle',
                13 => 'Malla Hukkanen',
                14 => 'Mika Ailasmäki',
                15 => 'Anne Vahlsten',
                16 => 'Kalle Penttilä',
                17 => 'Ville Väänänen',
                18 => 'Éric Garzena',
                19 => 'Cyril Dupont',
                20 => 'Lazar Abdelkebir',
                21 => 'Benjamin Laurent',
                22 => 'Tero Malmberg',
                23 => 'Konsta Hormia',
                24 => 'Iisakki Hormia',
                25 => 'Olli Pärnänen',
                26 => 'Thomas Pitre',
                27 => 'Pomme Delépine',
                28 => 'Ireneusz (Irek) Spiewak',
                29 => 'Gérard Simonet',
                30 => 'Jean-Claude Guilleman',
                31 => 'Sébastien Gallien',
                32 => 'Pascal Courtinel',
                33 => 'Laurent Thévenot',
                34 => 'Clara Lyonnet',
                35 => 'Diane Wehrly',
                36 => 'Paula Oinonen',
                37 => 'Élise Pradinas',
                38 => 'Elsa Pharaon',
                39 => 'Jean Eninger',
                40 => 'Augustin Werkoff',
                41 => 'Guillaume Moinard',
                42 => 'Marine Longuet',
                43 => 'Pauline Reichenbach',
                44 => 'Yoann Le Gruiec',
                45 => 'Agnès Fanget',
                46 => 'Stéphanie Jossec',
                47 => 'Frank Lesniak',
                48 => 'Frédéric Sibeud',
                49 => 'Thibault Spiral',
                50 => 'Mathieu Raab',
                51 => 'Lucien Lefèbvre',
                52 => 'Éric Morel',
                53 => 'Didier Guéroult',
                54 => 'Gilbert Devaux',
                55 => 'Bruno Joignant',
                56 => 'Thomas Guérin',
                57 => 'Stéphane Livonnen',
                58 => 'Patrice Campelli',
                59 => 'Karl Lemeray',
                60 => 'Jean-Marie Paillette',
                61 => 'Guillaume Macquet',
                62 => 'Patrick Leboucher',
                63 => 'Ève Bruant',
                64 => 'Hanna Hemilä',
                65 => 'Haije Tulokas',
                66 => 'Eevi Kareinen',
                67 => 'Kirsi Hatara',
                68 => 'Heikki Keskinen',
                69 => 'Stéphane Parthenay',
                70 => 'Valérie Farthouat',
                71 => 'Philippe Leconte',
                72 => 'Anne Berjon',
                73 => 'Fanette Martinie',
                74 => 'Louise Lehec',
                75 => 'Karl Baumgartner',
                76 => 'Rainer Teusner',
                77 => 'Viola Fügen',
                78 => 'Camelia Förster',
                79 => 'Frédéric Baroudel',
                80 => 'Catherine Athon',
                81 => 'Frédéric Casnin',
                82 => 'Frédéric Jupin',
                83 => 'Dominique Champel',
                84 => 'Gérard Estival',
                85 => 'Thierry Gazaud',
                86 => 'Franck Tassoul',
                87 => 'Eric Sithavaja',
                88 => 'Jan-Eric Nyström',
                89 => 'Cinéstéréo',
                90 => 'Sputnik Oy',
                91 => 'Ciné Lumières de Paris',
                92 => 'Cinésyl',
                93 => 'Cinéma le studio Le Havre',
                94 => 'Studio Honolulu',
                95 => 'Ptit Bernard Location',
                96 => 'ATP Autocars',
                97 => 'Bus Océane',
                98 => 'Association La Roue en Bois',
                99 => 'Groupe TSF',
                100 => 'Cinéboutique',
                101 => 'Maratier',
                102 => 'Le Vestiaire',
                103 => 'Any d\'Avray',
                104 => 'Rubini & Associés',
                105 => 'Yrittäjäin Fennia',
                106 => 'Paula Oinonen',
            ],
            'author_role' => [
                0 => 'd02',
                1 => 'a99',
                2 => 'a99',
                3 => 'a99',
                4 => 'a99',
                5 => 'a99',
                6 => 'a99',
                7 => 'a99',
                8 => 'a99',
                9 => 'a99',
                10 => 'a99',
                11 => 'a99',
                12 => 'a99',
                13 => 'a99',
                14 => 'a99',
                15 => 'a99',
                16 => 'a99',
                17 => 'a99',
                18 => 'a99',
                19 => 'a99',
                20 => 'a99',
                21 => 'a99',
                22 => 'a99',
                23 => 'a99',
                24 => 'a99',
                25 => 'a99',
                26 => 'a99',
                27 => 'a99',
                28 => 'a99',
                29 => 'a99',
                30 => 'a99',
                31 => 'a99',
                32 => 'a99',
                33 => 'a99',
                34 => 'a99',
                35 => 'a99',
                36 => 'a99',
                37 => 'a99',
                38 => 'a99',
                39 => 'a99',
                40 => 'a99',
                41 => 'a99',
                42 => 'a99',
                43 => 'a99',
                44 => 'a99',
                45 => 'a99',
                46 => 'a99',
                47 => 'a99',
                48 => 'a99',
                49 => 'a99',
                50 => 'a99',
                51 => 'a99',
                52 => 'a99',
                53 => 'a99',
                54 => 'a99',
                55 => 'a99',
                56 => 'a99',
                57 => 'a99',
                58 => 'a99',
                59 => 'a99',
                60 => 'a99',
                61 => 'a99',
                62 => 'a99',
                63 => 'a99',
                64 => 'a99',
                65 => 'a99',
                66 => 'a99',
                67 => 'a99',
                68 => 'a99',
                69 => 'a99',
                70 => 'a99',
                71 => 'a99',
                72 => 'a99',
                73 => 'a99',
                74 => 'a99',
                75 => 'a99',
                76 => 'a99',
                77 => 'a99',
                78 => 'a99',
                79 => 'a99',
                80 => 'a99',
                81 => 'a99',
                82 => 'a99',
                83 => 'a99',
                84 => 'a99',
                85 => 'a99',
                86 => 'a99',
                87 => 'a99',
                88 => 'a99',
                89 => 'a99',
                90 => 'a99',
                91 => 'a99',
                92 => 'a99',
                93 => 'a99',
                94 => 'a99',
                95 => 'a99',
                96 => 'a99',
                97 => 'a99',
                98 => 'a99',
                99 => 'a99',
                100 => 'a99',
                101 => 'a99',
                102 => 'a99',
                103 => 'a99',
                104 => 'a99',
                105 => 'a99',
                106 => 'a99',
            ],
            'author_sort' => 'Aki Kaurismäki',
            'author2' => [
                0 => 'André Wilms',
                1 => 'Kati Outinen',
                2 => 'Jean-Pierre Darroussin',
                3 => 'Blondin Miguel',
                4 => 'Elina Salo',
                5 => 'Evelyne Didi',
                6 => 'Quoc Dung Nguyen',
                7 => 'François Monnié',
                8 => 'Roberto Piazza',
                9 => 'Pierre Étaix',
                10 => 'Jean-Pierre Léaud',
                11 => 'Vincent Lebodo',
                12 => 'Umbañ Uksët',
                13 => 'Patrick Bonnel',
                14 => 'Ilkka Koivula',
                15 => 'Myriam "Mimie" Piazza',
                16 => 'Luce Vigo',
                17 => 'Valérie Caron',
                18 => 'Jérôme Boyer',
                19 => 'Jean-Luc Guion-Firmin',
                20 => 'Pierre Morineau',
                21 => 'Johann Rioux',
                22 => 'Julien Flematti',
                23 => 'Éric Duteil',
                24 => 'Corinne Belet',
                25 => 'Dominique Lepagne',
                26 => 'Anne Lizy',
                27 => 'Pierre Richards',
                28 => 'Loïck Jamet',
                29 => 'Little Bob',
                30 => 'Nico Garotin',
                31 => 'Bertrand Couloume',
                32 => 'Nicolas Noël',
                33 => 'Gilles Mallet',
                34 => 'Gilles Adam',
                35 => 'Patrick Leboucher',
                36 => 'Michel Lacaille',
                37 => 'Stéphane Livonnen',
                38 => 'Arnaud Clément',
                39 => 'Dominique Comont',
                40 => 'Alain Guillot',
                41 => 'Philippe Hubschwerlin',
                42 => 'Franck Durand',
                43 => 'Christian Amyard',
                44 => 'Rudy Amyard',
                45 => 'Brice Augé',
                46 => 'Lucas Loubaresse',
                47 => 'Ireneusz (Irek) Spiewak',
                48 => 'Gilles Charmant',
                49 => 'Mary Berkelmans',
                50 => 'Seluna Lemercier',
                51 => 'Fanette Martinie',
                52 => 'Rémi Pradinas',
                53 => 'Stéphane Parthenay',
                54 => 'Alain Chapelain',
                55 => 'Gilles Adam',
                56 => 'Rachid Bessal',
                57 => 'Oumar Ly',
                58 => 'Emmanuel Ingweiller',
                59 => 'Matthieu Hébert',
                60 => 'Frank Atinault',
                61 => 'Dominique Mare',
                62 => 'Brice Niel',
                63 => 'Alban Rutten',
                64 => 'Franck Rutten',
            ],
            'author2_role' => [
                0 => 'e01',
                1 => 'e01',
                2 => 'e01',
                3 => 'e01',
                4 => 'e01',
                5 => 'e01',
                6 => 'e01',
                7 => 'e01',
                8 => 'e01',
                9 => 'e01',
                10 => 'e01',
                11 => 'e01',
                12 => 'e01',
                13 => 'e01',
                14 => 'e01',
                15 => 'e01',
                16 => 'e01',
                17 => 'e01',
                18 => 'e01',
                19 => 'e01',
                20 => 'e01',
                21 => 'e01',
                22 => 'e01',
                23 => 'e01',
                24 => 'e01',
                25 => 'e01',
                26 => 'e01',
                27 => 'e01',
                28 => 'e01',
                29 => 'e01',
                30 => 'e01',
                31 => 'e01',
                32 => 'e01',
                33 => 'e01',
                34 => 'e01',
                35 => 'e01',
                36 => 'e01',
                37 => 'e01',
                38 => 'e01',
                39 => 'e01',
                40 => 'e01',
                41 => 'e01',
                42 => 'e01',
                43 => 'e01',
                44 => 'e01',
                45 => 'e01',
                46 => 'e01',
                47 => 'e01',
                48 => 'e01',
                49 => 'e01',
                50 => 'e01',
                51 => 'e01',
                52 => 'e01',
                53 => 'e01',
                54 => 'e01',
                55 => 'e01',
                56 => 'e01',
                57 => 'e01',
                58 => 'e01',
                59 => 'e01',
                60 => 'e01',
                61 => 'e01',
                62 => 'e01',
                63 => 'e01',
                64 => 'e01',
            ],
            'author_corporate' => [
                0 => 'Aki Kaurismäki',
                1 => 'Aki Kaurismäki',
                2 => 'Aki Kaurismäki',
                3 => 'Timo Salminen',
                4 => 'Timo Linnasalo',
                5 => 'Tero Malmberg',
                6 => 'Wouter Zoon',
                7 => 'Fred Cambier',
                8 => 'Valérie Théry-Hamel',
                9 => 'Gilles Charmant',
                10 => 'Olli Varja',
                11 => 'Claire Langmann',
                12 => 'Rémi Pradinas',
                13 => 'Mark Lwoff',
                14 => 'Fabienne Vonier',
                15 => 'Reinhard Brundig',
                16 => 'Michel Reilhac',
                17 => 'Rémi Burah',
                18 => 'Meinolf Zurhorst',
                19 => 'Lucas Loubaresse',
                20 => 'Renaud Gast',
                21 => 'Irmeli Debarle',
                22 => 'Malla Hukkanen',
                23 => 'Mika Ailasmäki',
                24 => 'Anne Vahlsten',
                25 => 'Kalle Penttilä',
                26 => 'Ville Väänänen',
                27 => 'Éric Garzena',
                28 => 'Cyril Dupont',
                29 => 'Lazar Abdelkebir',
                30 => 'Benjamin Laurent',
                31 => 'Tero Malmberg',
                32 => 'Konsta Hormia',
                33 => 'Iisakki Hormia',
                34 => 'Olli Pärnänen',
                35 => 'Thomas Pitre',
                36 => 'Pomme Delépine',
                37 => 'Ireneusz (Irek) Spiewak',
                38 => 'Gérard Simonet',
                39 => 'Jean-Claude Guilleman',
                40 => 'Sébastien Gallien',
                41 => 'Pascal Courtinel',
                42 => 'Laurent Thévenot',
                43 => 'Clara Lyonnet',
                44 => 'Diane Wehrly',
                45 => 'Paula Oinonen',
                46 => 'Élise Pradinas',
                47 => 'Elsa Pharaon',
                48 => 'Jean Eninger',
                49 => 'Augustin Werkoff',
                50 => 'Guillaume Moinard',
                51 => 'Marine Longuet',
                52 => 'Pauline Reichenbach',
                53 => 'Yoann Le Gruiec',
                54 => 'Agnès Fanget',
                55 => 'Stéphanie Jossec',
                56 => 'Frank Lesniak',
                57 => 'Frédéric Sibeud',
                58 => 'Thibault Spiral',
                59 => 'Mathieu Raab',
                60 => 'Lucien Lefèbvre',
                61 => 'Éric Morel',
                62 => 'Didier Guéroult',
                63 => 'Gilbert Devaux',
                64 => 'Bruno Joignant',
                65 => 'Thomas Guérin',
                66 => 'Stéphane Livonnen',
                67 => 'Patrice Campelli',
                68 => 'Karl Lemeray',
                69 => 'Jean-Marie Paillette',
                70 => 'Guillaume Macquet',
                71 => 'Patrick Leboucher',
                72 => 'Irmeli Debarle',
                73 => 'Mikko Lyytikäinen',
                74 => 'Ève Bruant',
                75 => 'Hanna Hemilä',
                76 => 'Haije Tulokas',
                77 => 'Eevi Kareinen',
                78 => 'Kirsi Hatara',
                79 => 'Heikki Keskinen',
                80 => 'Stéphane Parthenay',
                81 => 'Valérie Farthouat',
                82 => 'Philippe Leconte',
                83 => 'Anne Berjon',
                84 => 'Fanette Martinie',
                85 => 'Louise Lehec',
                86 => 'Karl Baumgartner',
                87 => 'Rainer Teusner',
                88 => 'Viola Fügen',
                89 => 'Camelia Förster',
                90 => 'Frédéric Baroudel',
                91 => 'Catherine Athon',
                92 => 'Frédéric Casnin',
                93 => 'Frédéric Jupin',
                94 => 'Dominique Champel',
                95 => 'Gérard Estival',
                96 => 'Thierry Gazaud',
                97 => 'Franck Tassoul',
                98 => 'Eric Sithavaja',
                99 => 'Jan-Eric Nyström',
                100 => 'Cinéstéréo',
                101 => 'Sputnik Oy',
                102 => 'Ciné Lumières de Paris',
                103 => 'Cinésyl',
                104 => 'Cinéma le studio Le Havre',
                105 => 'Studio Honolulu',
                106 => 'Ptit Bernard Location',
                107 => 'ATP Autocars',
                108 => 'Bus Océane',
                109 => 'Association La Roue en Bois',
                110 => 'Groupe TSF',
                111 => 'Cinéboutique',
                112 => 'Maratier',
                113 => 'Le Vestiaire',
                114 => 'Any d\'Avray',
                115 => 'Rubini & Associés',
                116 => 'Yrittäjäin Fennia',
                117 => 'André Wilms',
                118 => 'Kati Outinen',
                119 => 'Jean-Pierre Darroussin',
                120 => 'Blondin Miguel',
                121 => 'Elina Salo',
                122 => 'Evelyne Didi',
                123 => 'Quoc Dung Nguyen',
                124 => 'François Monnié',
                125 => 'Roberto Piazza',
                126 => 'Pierre Étaix',
                127 => 'Jean-Pierre Léaud',
                128 => 'Vincent Lebodo',
                129 => 'Umbañ Uksët',
                130 => 'Patrick Bonnel',
                131 => 'Ilkka Koivula',
                132 => 'Myriam "Mimie" Piazza',
                133 => 'Luce Vigo',
                134 => 'Valérie Caron',
                135 => 'Jérôme Boyer',
                136 => 'Jean-Luc Guion-Firmin',
                137 => 'Pierre Morineau',
                138 => 'Johann Rioux',
                139 => 'Julien Flematti',
                140 => 'Éric Duteil',
                141 => 'Corinne Belet',
                142 => 'Dominique Lepagne',
                143 => 'Anne Lizy',
                144 => 'Pierre Richards',
                145 => 'Loïck Jamet',
                146 => 'Little Bob',
                147 => 'Nico Garotin',
                148 => 'Bertrand Couloume',
                149 => 'Nicolas Noël',
                150 => 'Gilles Mallet',
                151 => 'Gilles Adam',
                152 => 'Patrick Leboucher',
                153 => 'Michel Lacaille',
                154 => 'Stéphane Livonnen',
                155 => 'Arnaud Clément',
                156 => 'Dominique Comont',
                157 => 'Alain Guillot',
                158 => 'Philippe Hubschwerlin',
                159 => 'Franck Durand',
                160 => 'Christian Amyard',
                161 => 'Rudy Amyard',
                162 => 'Brice Augé',
                163 => 'Lucas Loubaresse',
                164 => 'Ireneusz (Irek) Spiewak',
                165 => 'Gilles Charmant',
                166 => 'Mary Berkelmans',
                167 => 'Seluna Lemercier',
                168 => 'Fanette Martinie',
                169 => 'Rémi Pradinas',
                170 => 'Stéphane Parthenay',
                171 => 'Alain Chapelain',
                172 => 'Gilles Adam',
                173 => 'Rachid Bessal',
                174 => 'Oumar Ly',
                175 => 'Emmanuel Ingweiller',
                176 => 'Matthieu Hébert',
                177 => 'Frank Atinault',
                178 => 'Dominique Mare',
                179 => 'Brice Niel',
                180 => 'Alban Rutten',
                181 => 'Franck Rutten',
                182 => 'Sputnik Oy',
                183 => 'Pyramide Productions',
                184 => 'Pandora Filmproduktion GmbH',
                185 => 'Arte France Cinéma',
                186 => 'ZDF / ARTE',
                187 => 'Suomen elokuvasäätiö SES',
                188 => 'Canal+',
                189 => 'Nordisk Film & TV Fond NFTF',
                190 => 'Le Centre National du Cinéma et de l\'Image Animée',
                191 => 'YLE Yhteistuotannot',
                192 => 'CinéCinéma',
                193 => 'Arte France',
                194 => 'Arte G.E.I.E.',
                195 => 'Suomen elokuvasäätiö SES',
                196 => 'Suomen elokuvasäätiö SES',
                197 => 'Suomen elokuvasäätiö SES',
                198 => 'Future Film Oy',
                199 => 'Future Film Oy',
                200 => 'The Match Factory GmbH',
                201 => 'Paula Oinonen',
            ],
            'author_corporate_role' => [
                0 => 'd02',
                1 => 'aus',
                2 => 'fmp',
                3 => 'cng',
                4 => 'flm',
                5 => 'sds',
                6 => 'std',
                7 => 'a99',
                8 => 'a99',
                9 => 'a99',
                10 => 'lgd',
                11 => 'a99',
                12 => 'pmn',
                13 => 'pmn',
                14 => 'a99',
                15 => 'a99',
                16 => 'a99',
                17 => 'a99',
                18 => 'a99',
                19 => 'a99',
                20 => 'a99',
                21 => 'a99',
                22 => 'a99',
                23 => 'a99',
                24 => 'a99',
                25 => 'a99',
                26 => 'a99',
                27 => 'a99',
                28 => 'a99',
                29 => 'a99',
                30 => 'a99',
                31 => 'a99',
                32 => 'a99',
                33 => 'a99',
                34 => 'a99',
                35 => 'a99',
                36 => 'a99',
                37 => 'a99',
                38 => 'a99',
                39 => 'a99',
                40 => 'a99',
                41 => 'a99',
                42 => 'a99',
                43 => 'a99',
                44 => 'a99',
                45 => 'a99',
                46 => 'a99',
                47 => 'a99',
                48 => 'a99',
                49 => 'a99',
                50 => 'a99',
                51 => 'a99',
                52 => 'a99',
                53 => 'a99',
                54 => 'a99',
                55 => 'a99',
                56 => 'a99',
                57 => 'a99',
                58 => 'a99',
                59 => 'a99',
                60 => 'a99',
                61 => 'a99',
                62 => 'a99',
                63 => 'a99',
                64 => 'a99',
                65 => 'a99',
                66 => 'a99',
                67 => 'a99',
                68 => 'a99',
                69 => 'a99',
                70 => 'a99',
                71 => 'a99',
                72 => 'trl',
                73 => 'trl',
                74 => 'a99',
                75 => 'a99',
                76 => 'a99',
                77 => 'a99',
                78 => 'a99',
                79 => 'a99',
                80 => 'a99',
                81 => 'a99',
                82 => 'a99',
                83 => 'a99',
                84 => 'a99',
                85 => 'a99',
                86 => 'a99',
                87 => 'a99',
                88 => 'a99',
                89 => 'a99',
                90 => 'a99',
                91 => 'a99',
                92 => 'a99',
                93 => 'a99',
                94 => 'a99',
                95 => 'a99',
                96 => 'a99',
                97 => 'a99',
                98 => 'a99',
                99 => 'a99',
                100 => 'a99',
                101 => 'a99',
                102 => 'a99',
                103 => 'a99',
                104 => 'a99',
                105 => 'a99',
                106 => 'a99',
                107 => 'a99',
                108 => 'a99',
                109 => 'a99',
                110 => 'a99',
                111 => 'a99',
                112 => 'a99',
                113 => 'a99',
                114 => 'a99',
                115 => 'a99',
                116 => 'a99',
                117 => 'e01',
                118 => 'e01',
                119 => 'e01',
                120 => 'e01',
                121 => 'e01',
                122 => 'e01',
                123 => 'e01',
                124 => 'e01',
                125 => 'e01',
                126 => 'e01',
                127 => 'e01',
                128 => 'e01',
                129 => 'e01',
                130 => 'e01',
                131 => 'e01',
                132 => 'e01',
                133 => 'e01',
                134 => 'e01',
                135 => 'e01',
                136 => 'e01',
                137 => 'e01',
                138 => 'e01',
                139 => 'e01',
                140 => 'e01',
                141 => 'e01',
                142 => 'e01',
                143 => 'e01',
                144 => 'e01',
                145 => 'e01',
                146 => 'e01',
                147 => 'e01',
                148 => 'e01',
                149 => 'e01',
                150 => 'e01',
                151 => 'e01',
                152 => 'e01',
                153 => 'e01',
                154 => 'e01',
                155 => 'e01',
                156 => 'e01',
                157 => 'e01',
                158 => 'e01',
                159 => 'e01',
                160 => 'e01',
                161 => 'e01',
                162 => 'e01',
                163 => 'e01',
                164 => 'e01',
                165 => 'e01',
                166 => 'e01',
                167 => 'e01',
                168 => 'e01',
                169 => 'e01',
                170 => 'e01',
                171 => 'e01',
                172 => 'e01',
                173 => 'e01',
                174 => 'e01',
                175 => 'e01',
                176 => 'e01',
                177 => 'e01',
                178 => 'e01',
                179 => 'e01',
                180 => 'e01',
                181 => 'e01',
                182 => 'e10',
                183 => 'e10',
                184 => 'e10',
                185 => 'e10',
                186 => 'e10',
                187 => 'fnd',
                188 => 'fnd',
                189 => 'fnd',
                190 => 'fnd',
                191 => 'fnd',
                192 => 'fnd',
                193 => 'fnd',
                194 => 'fnd',
                195 => 'fnd',
                196 => 'fnd',
                197 => 'fnd',
                198 => 'fds',
                199 => 'fds',
                200 => 'fds',
                201 => 'a99',
            ],
            'geographic_facet' => [
                0 => 'Suomi',
                1 => 'Ranska',
                2 => 'Saksa',
            ],
            'geographic' => [
                0 => 'Suomi',
                1 => 'Ranska',
                2 => 'Saksa',
            ],
            'genre_facet' => [],
            'genre' => [],
            'format' => 'MotionPicture',
            'publisher' => [],
            'allfields' => [
                'Le Havre',
                'Le Havre',
                'Le Havre',
                'Mannen från Le Havre',
                'Le Havre',
                'Le Havre',
                'Le Havre',
                'El Havre',
                'El Puerto',
                'El Puerto',
                'Le Havre: el puerto de la esperanza',
                'Hof mivtahim',
                'Miracolo a Le Havre',
                'To limani tis Havris',
                'Havras',
                'Le Havre',
                'O Porto',
                'Czlowiek z Hawru',
                'Miraklet i Le Havre',
                'Umut Limani',
                'Kikötői történet',
                'Gavr',
                'Le Havre: Sadamalinn',
                'Le Havre',
                'Suomi',
                'Ranska',
                'Saksa',
                '2011',
                'Aki Kaurismäki',
                'Aki Kaurismäki',
                'Aki Kaurismäki',
                'Timo Salminen',
                'Timo Linnasalo',
                'Tero Malmberg',
                'Wouter Zoon',
                'Fred Cambier',
                'Valérie Théry-Hamel',
                'Gilles Charmant',
                'Olli Varja',
                'Claire Langmann',
                'Rémi Pradinas',
                'Mark Lwoff',
                'Fabienne Vonier',
                'Reinhard Brundig',
                'Michel Reilhac',
                'Rémi Burah',
                'Meinolf Zurhorst',
                'Lucas Loubaresse',
                'Renaud Gast',
                'Irmeli Debarle',
                'Malla Hukkanen',
                'Mika Ailasmäki',
                'Anne Vahlsten',
                'Kalle Penttilä',
                'Ville Väänänen',
                'Éric Garzena',
                'Cyril Dupont',
                'Lazar Abdelkebir',
                'Benjamin Laurent',
                'Tero Malmberg',
                'Konsta Hormia',
                'Iisakki Hormia',
                'Olli Pärnänen',
                'Thomas Pitre',
                'Pomme Delépine',
                'Ireneusz (Irek) Spiewak',
                'Gérard Simonet',
                'Jean-Claude Guilleman',
                'Sébastien Gallien',
                'Pascal Courtinel',
                'Laurent Thévenot',
                'Clara Lyonnet',
                'Diane Wehrly',
                'Paula Oinonen',
                'Élise Pradinas',
                'Elsa Pharaon',
                'Jean Eninger',
                'Augustin Werkoff',
                'Guillaume Moinard',
                'Marine Longuet',
                'Pauline Reichenbach',
                'Yoann Le Gruiec',
                'Agnès Fanget',
                'Stéphanie Jossec',
                'Frank Lesniak',
                'Frédéric Sibeud',
                'Thibault Spiral',
                'Mathieu Raab',
                'Lucien Lefèbvre',
                'Éric Morel',
                'Didier Guéroult',
                'Gilbert Devaux',
                'Bruno Joignant',
                'Thomas Guérin',
                'Stéphane Livonnen',
                'Patrice Campelli',
                'Karl Lemeray',
                'Jean-Marie Paillette',
                'Guillaume Macquet',
                'Patrick Leboucher',
                'Irmeli Debarle',
                'Mikko Lyytikäinen',
                'Ève Bruant',
                'Hanna Hemilä',
                'Haije Tulokas',
                'Eevi Kareinen',
                'Kirsi Hatara',
                'Heikki Keskinen',
                'Stéphane Parthenay',
                'Valérie Farthouat',
                'Philippe Leconte',
                'Anne Berjon',
                'Fanette Martinie',
                'Louise Lehec',
                'Karl Baumgartner',
                'Rainer Teusner',
                'Viola Fügen',
                'Camelia Förster',
                'Frédéric Baroudel',
                'Catherine Athon',
                'Frédéric Casnin',
                'Frédéric Jupin',
                'Dominique Champel',
                'Gérard Estival',
                'Thierry Gazaud',
                'Franck Tassoul',
                'Eric Sithavaja',
                'Jan-Eric Nyström',
                'Cinéstéréo',
                'Sputnik Oy',
                'Ciné Lumières de Paris',
                'Cinésyl',
                'Cinéma le studio Le Havre',
                'Studio Honolulu',
                'Ptit Bernard Location',
                'ATP Autocars',
                'Bus Océane',
                'Association La Roue en Bois',
                'Groupe TSF',
                'Cinéboutique',
                'Maratier',
                'Le Vestiaire',
                'Any d\'Avray',
                'Rubini & Associés',
                'Yrittäjäin Fennia',
                'André Wilms',
                'Kati Outinen',
                'Jean-Pierre Darroussin',
                'Blondin Miguel',
                'Elina Salo',
                'Evelyne Didi',
                'Quoc Dung Nguyen',
                'François Monnié',
                'Roberto Piazza',
                'Pierre Étaix',
                'Jean-Pierre Léaud',
                'Vincent Lebodo',
                'Umbañ Uksët',
                'Patrick Bonnel',
                'Ilkka Koivula',
                'Myriam "Mimie" Piazza',
                'Luce Vigo',
                'Valérie Caron',
                'Jérôme Boyer',
                'Jean-Luc Guion-Firmin',
                'Pierre Morineau',
                'Johann Rioux',
                'Julien Flematti',
                'Éric Duteil',
                'Corinne Belet',
                'Dominique Lepagne',
                'Anne Lizy',
                'Pierre Richards',
                'Loïck Jamet',
                'Little Bob',
                'Nico Garotin',
                'Bertrand Couloume',
                'Nicolas Noël',
                'Gilles Mallet',
                'Gilles Adam',
                'Patrick Leboucher',
                'Michel Lacaille',
                'Stéphane Livonnen',
                'Arnaud Clément',
                'Dominique Comont',
                'Alain Guillot',
                'Philippe Hubschwerlin',
                'Franck Durand',
                'Christian Amyard',
                'Rudy Amyard',
                'Brice Augé',
                'Lucas Loubaresse',
                'Ireneusz (Irek) Spiewak',
                'Gilles Charmant',
                'Mary Berkelmans',
                'Seluna Lemercier',
                'Fanette Martinie',
                'Rémi Pradinas',
                'Stéphane Parthenay',
                'Alain Chapelain',
                'Gilles Adam',
                'Rachid Bessal',
                'Oumar Ly',
                'Emmanuel Ingweiller',
                'Matthieu Hébert',
                'Frank Atinault',
                'Dominique Mare',
                'Brice Niel',
                'Alban Rutten',
                'Franck Rutten',
                'Sputnik Oy',
                'Pyramide Productions',
                'Pandora Filmproduktion GmbH',
                'Arte France Cinéma',
                'ZDF / ARTE',
                'Suomen elokuvasäätiö SES',
                'Canal+',
                'Nordisk Film & TV Fond NFTF',
                'Le Centre National du Cinéma et de l\'Image Animée',
                'YLE Yhteistuotannot',
                'CinéCinéma',
                'Arte France',
                'Arte G.E.I.E',
                'Suomen elokuvasäätiö SES',
                'Suomen elokuvasäätiö SES',
                'Suomen elokuvasäätiö SES',
                'Future Film Oy',
                'Future Film Oy',
                'The Match Factory GmbH',
                'Paula Oinonen',
                '11.08.2011',
                '15.04.2014',
                'Cannes, Ranska',
                '2011',
                'Sodankylä, Suomi',
                '2011',
                'Bratislava, Slovakia',
                '2011',
                'München, Saksa',
                '2011',
                'Karlovy Vary, Tšekki',
                '2011',
                'Pietari, Venäjä',
                '2011',
                'Melbourne, Australia',
                '2011',
                'Odessa, Ukraina',
                '2011',
                'Wroclaw, Puola',
                '2011',
                'Sarajevo, Bosnia ja Hertsegovina',
                '2011',
                'Uherské Hradiště, Tšekki',
                '2011',
                'Locarno, Sveitsi',
                '2011',
                'San Sebastián, Espanja',
                '2011',
                'Toronto (ON), Kanada',
                '2011',
                'Vladivostok, Venäjä',
                '2011',
                'Quebec (QC), Kanada',
                '2011',
                'Reykjavik, Islanti',
                '2011',
                'Edmonton (AB), Kanada',
                '2011',
                'New York (NY), Yhdysvallat',
                '2011',
                'Rio de Janeiro, Brasilia',
                '2011',
                'Valdivia, Chile',
                '2011',
                'Bukarest, Romania',
                '2011',
                'Wien, Itävalta',
                '2011',
                'Kaliningrad, Venäjä',
                '2011',
                'Taipei, Taiwan',
                '2011',
                'Chicago (IL), Yhdysvallat',
                '2011',
                'Busan, Etelä-Korea',
                '2011',
                'Morelia, Meksiko',
                '2011',
                'Honolulu (HI), Yhdysvallat',
                '2011',
                'Santa Fe (NM), Yhdysvallat',
                '2011',
                'Denver (CO), Yhdysvallat',
                '2011',
                'Montreal (QC), Kanada',
                '2011',
                'Malatya, Turkki',
                '2011',
                'Mexico City, Meksiko',
                '2011',
                'Tukholma, Ruotsi',
                '2011',
                'Ankara, Turkki',
                '2011',
                'Torino, Italia',
                '2011',
                'Buenos Aires, Argentiina',
                '2011',
                'Kiova, Ukraina',
                '2011',
                'Dubai, Yhdistyneet arabiemiirikunnat',
                '2011',
                'Bydgoszcz, Puola',
                '2011',
                'Chennai (Tamil Nadu), Intia',
                '2011',
                'Palm Springs (CA), Yhdysvallat',
                '2012',
                'Rotterdam, Alankomaat',
                '2012',
                'Glasgow, Iso-Britannia',
                '2012',
                'Pinamar, Argentiina',
                '2012',
                'Belgrad, Serbia',
                '2012',
                'Eskişehir, Turkki',
                '2012',
                'Durban, Etelä-Afrikka',
                '2012',
                'Hongkong, Kiina',
                '2012',
                'Rauma, Suomi',
                '2012',
                'Espoo, Suomi',
                '2012',
                'Tokio, Japani',
                '2012',
                'Thessaloniki, Kreikka',
                '2012',
                'St. Louis (MO), Yhdysvallat',
                '2012',
                'Manila, Filippiinit',
                '2012',
                'Thiruvananthapuram, Intia',
                '2012',
                'Bangalore (Karnataka), Intia',
                '2012',
                '09.09.2011',
                'Espoo: Bio Rex Sello 4, Kino Tapiola, Omena 3; Forssa: Bio-Kaari;'
                    . ' Helsinki: Kinopalatsi 7, Tennispalatsi 2; Järvenpää: Studio'
                    . ' Järvenpää; Kuopio: Kuvakukko; Lahti: Kuvapalatsi, Kino'
                    . ' Iiris; Oulu: Plaza, Star; Pori: Promenadi 5; Tampere:'
                    . ' Niagara; Turku: Kinopalatsi 5 & 7; Vantaa: Bio Grand,'
                    . ' Flamingo 5, Kino Myyri',
                'Alankomaat',
                'Alankomaat',
                'Alankomaat',
                'Alankomaat',
                'Argentiina',
                'Argentiina',
                'Australia',
                'Belgia',
                'Belgia',
                'Brasilia',
                'Brasilia',
                'Bulgaria',
                'Bulgaria',
                'Chile',
                'Espanja',
                'Espanja',
                'Etelä-Korea',
                'Hongkong (Kiina)',
                'Hongkong (Kiina)',
                'Irlanti',
                'Iso-Britannia',
                'Iso-Britannia',
                'Israel',
                'Israel',
                'Italia',
                'Italia',
                'Itsenäisten valtioiden yhteisö',
                'Itävalta',
                'Itävalta',
                'Japani',
                'Japani',
                'Kanada',
                'Kanada',
                'Kiina',
                'Kolumbia',
                'Kolumbia',
                'Kreikka',
                'Kreikka',
                'Kroatia',
                'Latvia',
                'Liettua',
                'Liettua',
                'Luxemburg',
                'Luxemburg',
                'Meksiko',
                'Meksiko',
                'Norja',
                'Paraguay',
                'Peru',
                'Portugali',
                'Portugali',
                'Puola',
                'Puola',
                'Ranska',
                'Romania',
                'Romania',
                'Ruotsi',
                'Ruotsi',
                'Ruotsi',
                'Saksa',
                'Serbia',
                'Serbia',
                'Slovakia',
                'Slovakia',
                'Slovenia',
                'Sveitsi',
                'Taiwan',
                'Tanska',
                'Tanska',
                'Tšekki',
                'Tšekki',
                'Turkki',
                'Turkki',
                'Unkari',
                'Unkari',
                'Uruguay',
                'Uruguay',
                'Uusi-Seelanti',
                'Uusi-Seelanti',
                'Venäjä',
                'Viro',
                'Viro',
                'Yhdysvallat',
                'Yhdysvallat',
                'Yhdysvallat',
                'Helsinki: Tennispalatsi [Eduskunnan näytös]',
                '08.09.2011',
                'ananas',
                'auttaminen',
                'avioliitto',
                'baarit',
                'kauppiaat',
                'koira',
                'konsertit',
                'laiton maahanmuutto',
                'laivat',
                'Le Havre',
                'maahanmuuttajat',
                'maahanmuuttopolitiikka',
                'naapuruus',
                'pakolaiset',
                'pakolaisleirit',
                'ihmeparantuminen',
                'poliisit',
                'Ranska',
                'ranskan kieli',
                'ravintolat',
                'rock',
                'sairastuminen',
                'sairaalat',
                'satamat',
                'siirtolaiset',
                'siirtolaisuus',
                'sosiaaliset ongelmat',
                'taudit',
                'viranomaiset',
                'vähävaraisuus',
                'ystävyys',
                'Cannesin elokuvajuhlat, Cannes, Ranska 2011: FIPRESCI:n palkinto'
                    . '[...]',
                'Aki Kaurismäen ohjaama, tuottama ja käsikirjoittama <i>Le Havre</i>'
                    . '[...]',
                'Marcel Marx, entinen kirjailija, elää Ranskassa Le Havressa'
                    . ' vaatimattomasti kengänkiillottajana vaimonsa Arlettyn'
                    . ' kanssa[...]',
                'Marcel Marx, a former author and a well-known bohemian, has'
                    . ' retreated into a voluntary exile in the port city of Le'
                    . ' Havre[...]',
                '<i>Apotheosis</i><br />Einojuhani Rautavaara[...]',
                'fiktio',
                'Aki Kaurismäen tuore elokuva hurmasi kriitikot. ”Maailmassa on enää'
                    . ' harvoja ohjaajia, joiden persoonallisen käsialan tunnistaa'
                    . ' heti filmin ensimmäisestä otoksesta lähtien”, aloitti Tapani'
                    . ' Maskula (Turun Sanomat 9.9.2011)',
                'Ohjaaja-tuottaja-käsikirjoittaja Aki Kaurismäki (s. 1957) on tehnyt'
                    . ' elokuvissa pitkän uran 1980-luvun alusta lähtien[...]',
                'Ranska: <br />Le Havre: <br />Rue des Drapiers (<I>Marcel'
                    . ' kiillottaa kenkiä rautatieasemalla, italialainen ammutaan,'
                    . ' Idrissa ja Laika pakenevat poliiseja</I>)[...]',
                'Ranska:<br />Le Havre: <br />tyhjillään ollut'
                    . ' kahvila-hotellirakennus 27 boulevard Amiral Mouchez[...]',
                'Ranska:<br />Le Havre: 45 rue Gustave Nicolle (<I>Marcelin ja'
                    . ' Arlettyn asunto ja sen puutarha[...]',
                'Marcelin asuinkorttelit aiottiin purkaa kesken elokuvan kuvausten.'
                    . ' Talot purettiin heti kun elokuva oli kuvattu[...]',
            ],
        ];

        $this->compareArray($expected, $fields, 'toSolrArray');

        $keys = $record->getWorkIdentificationData();

        $expected = [
            [
                'authors' => [
                    0 => [
                        'type' => 'author',
                        'value' => 'Kaurismäki, Aki',
                    ],
                ],
                'authorsAltScript' => [
                ],
                'titles' => [
                    0 => [
                        'type' => 'title',
                        'value' => 'havre',
                    ],
                    1 => [
                        'type' => 'title',
                        'value' => 'Le Havre',
                    ],
                ],
                'titlesAltScript' => [
                ],
            ]
        ];

        $this->compareArray($expected, $keys, 'getWorkIdentificationData');
    }
}
